### ISSUE TITLE
Update CCADB Policy section 4 to match v2.5 of Mozilla Root Store Policy

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#100]
Section 4 of the Common CCADB Policy needs to be updated to match version 2.5 of Mozilla's Root Store Policy.

Currently section 4 of the CCADB Policy says:
"Intermediate certificates are exempt from being added to the CCADB if at least one of the following is true:
    The certificate has the Extended Key Usage (EKU) extension and the EKU does not include the anyExtendedKeyUsage or id-kp-serverAuth KeyPurposeIds; "

But section 5.3.1 of version 2.5 of Mozilla's Root Store Policy says:
"If the certificate includes the id-kp-emailProtection extended key usage, it MUST include the Name Constraints X.509v3 extension with constraints on rfc822Name, with at least one name in permittedSubtrees, each such name having its ownership validated according to section 3.2.2.4 of the Baseline Requirements."
and section 5.3.2 says:
"All certificates that are capable of being used to issue new certificates, that are not technically constrained, and that directly or transitively chain to a certificate included in Mozilla’s root program MUST be audited in accordance with Mozilla’s Root Store Policy and MUST be publicly disclosed in the CCADB"

**Comment by gerv** [comment]
@WilsonKathleen The right solution may not be updating the CCADB policy. (And if we make this change, we'd need to clear it with other CCADB users, as it's a substantive change to a shared policy.)

Currently, our policy requires disclosure in the CCADB of all non-technically-constrained certificates that are in scope of our policy. Our policy covers both SSL and email. Are we sure we want to require disclosure of non-technically-constrained email intermediates? I think we do, but that's the first thing to confirm.

Do other CCADB users use the CCADB for managing their entire root programs, or just the SSL/TLS parts? If they use it for all parts, are there already CCADB features specific to code signing, or email, or other usages? Does the CCADB cope OK with intermediates without id-kp-serverAuth? Can it cope with non-DNS name constraints? (I know constrained certs don't currently have to be disclosed, but some people do it anyway.)

**Comment by wthayer** [comment]
Perhaps CCADB policy should just be updated to clarify that individual root programs may require more disclosure than the CCADB policy does.

**Comment by WilsonKathleen** [comment]
OK. Currently the second paragraph of
http://ccadb.org/policy#4-intermediate-certificates
is wrong:
"Intermediate certificates are exempt from being added to the CCADB if at least one of the following is true:"

But perhaps it could be corrected by changing it to something like:
"Intermediate certificates **may** be exempt from being added to the CCADB if at least one of the following is true. Check the disclosure requirements for the root programs that your root certificates are included in."

**Comment by wthayer** [comment]
@WilsonKathleen proposed the following change to section 4 to resolve this issue:

> 4. Intermediate Certificates
> 
> An intermediate certificate is a certificate that is signed by a root certificate, and is capable of issuing new certificates. To determine which intermediate certificates must be entered into the database, refer to the Store policy documents.
> 
> Each instance (i.e. PEM data) of an intermediate certificate only needs to be included in the CCADB once, even if it chains up to two root certificates.
> 
> If an intermediate certificate is revoked, the CCADB must be updated to mark it as revoked, giving the reason why, within 24 hours for a security incident, and within 7 days for any other reason.

I will contact participating root store operators for approval.

**Comment by wthayer** [comment]
Updated proposal based on feedback from Devon:

> 4.       Intermediate CA Certificates
> 
>  An intermediate CA certificate is a certificate capable of issuing new certificates that is not a root certificate. To determine which intermediate CA certificates must be entered into the CCADB, refer to the individual Store policy documents. This may include certificates that are revoked. Newly-created intermediate CA certificates must be entered into the database before the certificate begins issuing publicly-trusted certificates.
> 
> Each instance (i.e. PEM data) of an intermediate CA certificate only needs to be included in the CCADB once, even if it chains up to two root certificates.
> 
> If an intermediate CA certificate is revoked, the CCADB must be updated to mark it as revoked, giving the reason why, within 24 hours for a security incident, and within 7 days for any other reason

**Comment by wthayer** [comment]
Updated policy to defer to individual root store operators for disclosure requirements. Did not make the terminology change to Intermediate CA Certificates because Kathleen suggested that CAs may interpret it as only applying to intermediates operated by a third party.
