### ISSUE TITLE
CA Validation Practices must be secure

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#115]
Consider updating section 2.2 to require that validation methods with known vulnerabilities not be utilized, or only be utilized if the CA has implemented and disclosed a mitigation to the known vulnerability.

Also, consider if the statement "the applicant has registered the domain(s) referenced in the certificate or has been authorized by the domain registrant to act on their behalf" conflicts with any of the approved BR methods, and if so, what to change to harmonize our requirements.

**Comment by gerv** [comment]
> Consider updating section 2.2 to require that validation methods with known vulnerabilities not be utilized, or only be utilized if the CA has implemented and disclosed a mitigation to the known vulnerability.

How do we define "known vulnerability"? I think this would require a formal statement from Mozilla that we wanted changes to how a particular method was used (or for that method to be abandoned). And if that's the case, how would we make such a statement? Perhaps by changing our policy, or doing a CA Communication. So maybe we want instead to say:

"Validation methods are occasionally found to have security flaws. If this happens, Mozilla will communicate to CAs any modifications it requires to use of a method, up to and including discontinuing use. CAs must follow those requirements."

**Comment by sleevi** [comment]
@wthayer writes:
> or only be utilized if the CA has implemented and disclosed a mitigation to the known vulnerability.

Does that process include a Mozilla review of the mitigation for its acceptability? Or does it mean a CA can resume utilizing the method, provided they have implemented and disclosed the mitigation, even if the mitigation is inadequate or insufficient?

If the latter case, and resumption is allowed, you would also need to consider what impact, if any, it would have for certificates issued with the inadequate mitigation-but-known-vulnerability.

@gerv writes:
> And if that's the case, how would we make such a statement?

Given that all CAs are required to monitor m.d.s.p., is that an avenue of communication that Mozilla will use? Or are you ruling that out and implying that communication == "CA communication" == CCADB mass mail? Do your processes support such rapid response?

**Comment by gerv** [comment]
We're currently planning a CA Communication to be sent out soon, with a reminder of several important events, deadlines and ongoing discussions. If no survey is required, our process does support a fairly rapid response.

CAs are required to monitor m.d.s.p., because we don't want CAs saying "wow, we never heard about that discussion at all; we'd have liked to have had input" or that sort of thing. But I think it's not the channel for official communication of changes in policy.
