### ISSUE TITLE
Compliance date

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#117]
Add date by which CAs must comply to future versions of the policy.

**Comment by gerv** [comment]
For the record: historically we've considered this metadata and communicated it outside the policy itself. (It also means we can change compliance dates without shipping a new policy.) You can see historical compliance dates here:
https://wiki.mozilla.org/CA/Root_Store_Policy_Archive

However, I am not going to oppose moving this data into the policy itself. Although (and I know you haven't suggested it) putting the _publication_ date into the policy would be a bit of a pain.

**Comment by wthayer** [comment]
Set effective date for 2.6 version to July 1, 2018
