### ISSUE TITLE
Remove ETSI TS 102 042 and TS 101 456 Audits

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#126]
Version 2.5 of the policy states:

ETSI TS 102 042 and TS 101 456 audits are only acceptable for audit periods ending in July 2017 or earlier.

After July, remove this statement and the bullets for TS 102 042 and TS 101 456 from the list of acceptable audits.

**Comment by sleevi** [comment]
This would be after November, right? (Because of the +90 day for reporting delivery after the end of the period)

**Comment by wthayer** [comment]
The deadline was July 2017, so we are well past the +90 days. This is also a dup of issue #108 , so I'm closing it.
