### ISSUE TITLE
Permit email certificate validation of entire domain

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#127]
Clarify that section 2.2(2) allows an email service provider to issue certificates for any email address ending in a domain that has it's MX record directed to the provider.

"For a certificate capable of being used for digitally signing or encrypting email messages, the CA takes reasonable measures to verify that the entity submitting the request controls the email account associated with the email address referenced in the certificate or has been authorized by the email account holder to act on the account holder’s behalf."

Reference: https://groups.google.com/d/msg/mozilla.dev.security.policy/WX64sTEubvs/OOVU5GwkCQAJ

**Comment by BenWilson-Mozilla** [comment]
@wthayer Greetings! Has this issue been resolved, or are there nuances that could still be addressed (related to the first sentence of your post above)?

**Comment by wthayer** [comment]
I don't think the issue as described by Ryan Hurst in the thread linked above has been fully resolved, but the S/MIME WG is the right forum to address it, so this issue can be closed.
