### ISSUE TITLE
Update CCADB Policy - CAs can submit audit cases

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#128]
The second paragraph in section 3 needs to be updated now that we have Audit Cases.
Suggested text:

> If root certificate information needs to be updated, the CA should notify one of the Stores containing the certificate, because this information may only be edited by Stores. See the Store policy documents for Store contact information.
> 
> To update audit information for a root certificate, create an Audit Case <link: https://ccadb.org/cas/updates>.

**Comment by WilsonKathleen** [comment]
This issue was previously fixed.
