### ISSUE TITLE
Require non-discriminatory CA conduct

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#129]
In the thread referenced below, concerns were raised over CAs ability to DoS or censor websites by revoking their certificate, or by refusing to issue a certificate.

https://groups.google.com/d/msg/mozilla.dev.security.policy/NjMmyA6MxN0/asxTGD3dCAAJ

Consider adding a policy forbidding these practices, possibly modeled after ETSI's requirements:

If your CA is audited according ETSI 319 401, there is a clear obligation for a CA (aka TSP) "to issue to those meeting the qualifications specified"

* REQ-7.1.1-02: Trust service practices under which the TSP operates shall be non-discriminatory.
* REQ-7.1.1-03: The TSP should make its services accessible to all applicants whose activities fall within its declared field of operation and that agree to abide by their obligations as specified in the TSP's terms and conditions.

**Comment by RufusJWB** [comment]
Doing Google research on this, it shows that there is plenty of discussion around these terms. I think we should avoid to re-invent the wheel and invite a legal expert to support us.

**Comment by BenWilson-Mozilla** [comment]
Closing this issue per https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/alZrZfF8QVs/m/EsILtJeLAwAJ
