### ISSUE TITLE
Update Required WebTrust Audit Versions

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#130]
WebTrust publishes effective dates after which audits must be performed with a new version of the audit criteria: http://www.webtrust.org/principles-and-criteria/docs/item85436.pdf. The WebTrust effective date is compared to the date for the beginning of the audit period, so we may receive audit using older criteria up to 15 months after the WebTrust effective date.

Consider removing version numbers from section 3.1.1 and simply stating that the latest version of the audit criteria that is in effect MUST be used. Otherwise, update the versions to the latest.

**Comment by BenWilson-Mozilla** [comment]
This is a relatively minor change that can take place when we publish v. 2.7.1 of the MRSP.
