### ISSUE TITLE
Improve terminology and style

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#131]
- Consider changing "CA" to "TSP" when used to represent an organization.
- Use consistent language for "subordinate CA certificate", a.k.a. "intermediate certificate"
- Use bullets vs. numbering consistently
- Use "; and," and "; or," at the end of list items consistently
- Ask a copywriter to review and make other suggestions

**Comment by RufusJWB** [comment]
As much as I like the term "TSP" to make the difference between the operating organization and the CA certificate clear, just introducing this term doesn't seem to be so easy: https://github.com/cabforum/documents/pull/84#discussion_r167082124

**Comment by dzacharo** [comment]
@RufusJWB, the CA/Browser Forum Policy Review Working Group has worked extensively on this topic and has produced a recommendation on GitHub (https://github.com/cabforum/documents/blob/ClarifyCADefinition/docs/BR.md). It will be put to a ballot.

**Comment by BenWilson-Mozilla** [comment]
I will take this on as part of the version 2.8 MRSP revisions.

**Comment by BenWilson-Mozilla** [comment]
Instead of TSP, I'm thinking that we should use the term "CA operator", which we've used recently in some instances.

**Comment by RufusJWB** [comment]
> @RufusJWB, the CA/Browser Forum Policy Review Working Group has worked extensively on this topic and has produced a recommendation on GitHub (https://github.com/cabforum/documents/blob/ClarifyCADefinition/docs/BR.md). It will be put to a ballot.

@dzacharo the link seems to be down and in the current BRGs I can't find a definition for "CA Operator".

**Comment by BenWilson-Mozilla** [comment]
Discussion started here - https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/GcuDmFK-OfE/m/nZzEsYwTAQAJ
