### ISSUE TITLE
Make it clear that RFC9162 precertificates are covered by Mozilla policy

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#138]
Mozilla doesn't currently have a policy on CT, but we consider precertificates to be a binding intent to issue as described in the RFC, and thus in-scope for our policy. Make this explicit in the policy.

**Comment by wthayer** [comment]
Move this into policy: https://wiki.mozilla.org/CA/Required_or_Recommended_Practices#Precertificates

**Comment by BenWilson-Mozilla** [comment]
We could create a new "Section 5.4 Precertificates" (section 5 is titled, "Certificates").

**Comment by BenWilson-Mozilla** [comment]
What about this?

5.4 Precertificates
Certificate Transparency precertificates are considered by Mozilla to be a binding intent to issue a certificate, as described in [section 3.2.1 of RFC 9162](https://datatracker.ietf.org/doc/html/rfc9162#section-3.2.1), and thus in-scope for enforcing compliance with these requirements. Accordingly, CAs MUST be able to revoke and to provide certificate status services for each certificate that is presumed to exist based on the existence of a corresponding precertificate.

**Comment by sleevi** [comment]
Note that the draft Profiles work in the CA/Browser Forum tries to specifically address this as well, and perhaps more comprehensively.

**Comment by BenWilson-Mozilla** [comment]
To be more comprehensive, I suppose I should move more of this new policy section: https://wiki.mozilla.org/CA/Required_or_Recommended_Practices#Precertificates. I missed the full meaning of Wayne's comment above.

**Comment by BenWilson-Mozilla** [comment]
Here is another iteration:
5.4 Precertificates
Certificate Transparency precertificates are considered by Mozilla to be a binding intent to issue a certificate, as described in section 3.2.1 of RFC 9162, and thus in-scope for enforcing compliance with these requirements. Thus, 
•	if any certificates with the same serial number and issuer exist, and one cannot be verified as the precertificate matching the final certificate using the algorithms in RFC 9162, this will be considered misissuance;
•	issuance of a precertificate that does not comply with this policy is considered equal to misissuance of a final certificate;
•	a CA must be able to revoke a certificate presumed to exist, if revocation of the certificate is required under this policy, even if the final certificate does not actually exist; and
•	a CA must provide OCSP services and responses in accordance with this policy for all certificates presumed to exist based on the presence of a precertificate, even if the certificate does not actually exist.

**Comment by BenWilson-Mozilla** [comment]
Public discussion started here:  https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/Co65loD9i-0/m/JuioteIBAgAJ

**Comment by robstradling** [comment]
RFC9162 (CTv2) precertificates are CMS objects, whereas RFC6962 (CTv1) precertificates are X.509 certificates that contain a "poison" extension.  RFC9162, which was only published a couple of months ago, has not yet seen any adoption.  RFC6962 is what's currently deployed in the WebPKI.

I suggest updating your draft text so that both RFC6962 precertificates **and** RFC9162 precertificates are in scope for Mozilla's policy.
