### ISSUE TITLE
Consider specifying actions required when an audit is qualified

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#150]
In policy section 3.1.3, there is a small reference to qualified audits that could be expanded, for example state that:
* Mozilla expects CAs to confirm that they have remediated problems (perhaps within a certain period of time)
* Mozilla may require a PIT audit to confirm problems have been remediated
* Repeated audits containing the same qualification, however minor, may lead to sanctions

**Comment by BenWilson-Mozilla** [comment]
This issue can be handled as part of addressing Issue #155.   Therefore, I'm going to close it.
