### ISSUE TITLE
Require Management Assertions to list Non-compliance

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#154]
Consider adding an audit requirement that the Management's Assertions letter list all material issues of non-compliance that the CA is aware of occurring during the audit period. Be as specific as possible about what constitutes a "material issue". Set an effective date for this requirement.

**Comment by BenWilson-Mozilla** [comment]
I am unaware of any comparable management assertion in the ETSI audit framework.  We could make a note of this requirement in [section 2.4 of the Mozilla Root Store Policy](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#24-incidents) when we address [Issue 187](https://github.com/mozilla/pkipolicy/issues/187), which I think is related.

**Comment by tialaramex** [comment]
The wording still feels a bit clumsy, but I'm conscious that previous experience with this type of requirement is that (not just in the Web PKI) audit subjects will try to find a way to interpret "Tell us everything" as "Don't tell us about embarrassing stuff" and so it's more important to be crystal clear that's not acceptable than to find the most polished words.

**Comment by timfromdigicert** [comment]
Shouldn't this have the (audit) tag?

**Comment by BenWilson-Mozilla** [comment]
Closing this as it is covered by the auditor's letter requirement addressed with Issue #187 and there is not a corresponding management assertion letter for ETSI audits.
