### ISSUE TITLE
Plan to Integrate Secondary Documents into PKI Policy Repo

### ISSUE THREAD

**Issue by weirdscience** [mozilla/pkipolicy#161]
I noticed on the Mozilla CA page (https://wiki.mozilla.org/CA) there are a number of secondary documents that are important to CAs, but not incorporated into the Mozilla Root Store policy. Will these documents be integrated into the future or referenced?

Short list (not totally inclusive)
- CA Actions when responding to an incident (https://wiki.mozilla.org/CA/Responding_To_An_Incident)
- Req/Rec CA Practices (https://wiki.mozilla.org/CA/Required_or_Recommended_Practices)
- Forbidden/Problematic CA Practices (https://wiki.mozilla.org/CA/Forbidden_or_Problematic_Practices)
- Maintenance and Enforcement (https://wiki.mozilla.org/CA/Maintenance_and_Enforcement)

**Comment by weirdscience** [comment]
Thank you. It seems like some of the content is already in the policy. I could take a first crack at consolidating it also.

**Comment by wthayer** [comment]
@weirdscience I am aware of two specific items from the secondary documents that I want to move into policy as part of the 2.7 update: issues 158 and 168.

I did review the Forbidden practices page as part of the 2.6 policy update and moved what made sense into policy (issue 107).

I just reviewed these pages and didn't find anything else that I feel should be in policy. I believe these pages serve as useful explanation beyond the actual policy. Can you point to specific rules listed on these pages that you feel should be added to the Mozilla policy?

**Comment by weirdscience** [comment]
@wthayer it's really anything that has a must, shall, should, type of statement.

I noticed that they are incorporated through the application, but not directly in the policy. Not sure if that means that they only apply when an entity applies, but they become for informational purposes after a CA is admitted. 

If you incorporated the requirement type components into the CP, feel free to close this issue. Thanks!

**Comment by wthayer** [comment]
Closing this issue since it doesn't identify specific additions to the policy. Please open new issues when specific policies that need to be added are identified.
