### ISSUE TITLE
Require the disclosure of the CA software as part of the Bug Report

### ISSUE THREAD

**Issue by RufusJWB** [mozilla/pkipolicy#162]
As Bug Reports have the goal of improving the quality of the overall CA eco system, I would like to propose, that every Bug Report, as defined in chapter 7.1, should disclose a sufficient level of information about the used CA software. By disclosing this information, the community could identify patterns, whether incidents are somehow related to certain CA software products or architectures (e.g. home-brewn on top of OpenSSL). 

I think the following addition could reach this goal:

> 6. information about the CA software used to generate the certificates. As a minimum either (for [COTS](https://en.wikipedia.org/wiki/Commercial_off-the-shelf) solutions) the name, vendor and version of the used software, or (for home-brewn solutions) detailed information about the architecture incl. the name and version of used components.

**Comment by RufusJWB** [comment]
In the light of the discussion on the mailing list about the 46 misissued certificates by Krajowa Izba Rozliczeniowa S.A. and their used CA software I would like to revive this proposal.

**Comment by wthayer** [comment]
Closing as WONTFIX based on discussion at https://groups.google.com/d/msg/mozilla.dev.security.policy/692gP7HqtPM/wB_eHTQtBQAJ
