### ISSUE TITLE
Strengthen requirement for newly included roots to meet all current requirements

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#173]
In the past, exceptions have sometimes been granted to roots that don't meet current requirements such as strict RFC compliance (e.g. positive serial number) or continuous audit coverage. Consider strengthening the policy by modifying section 7.1 to state:

Before being included, CAs MUST provide evidence that their CA certificates fully comply with the current Mozilla Root Store Policy and Baseline Requirements, and have continually, from the time of creation, complied with the then-current Mozilla Root Store Policy and Baseline Requirements.

**Comment by BenWilson-Mozilla** [comment]
This issue alludes to the need for continuous audit coverage. In essence, this issue could be combined with [Issue 139](https://github.com/mozilla/pkipolicy/issues/139) and [Issue 153](https://github.com/mozilla/pkipolicy/issues/153).  @wthayer , I know that you have previously drafted some language surrounding this.  Here is another similar snippet for a change that could be made to the second sentence of BR section 8.1 - "Root and Subordinate CA Key Pairs and Certificates SHALL be audited continuously from the date of Key Pair Generation until [choose:  all certificates utilizing the Key Pair are revoked or expire OR until all copies of the Key Pair are destroyed]. Periodic audits during such "CA lifetime" [to be defined] SHALL be divided into an unbroken, contiguous sequence of audit periods not exceeding one year in duration.”
