### ISSUE TITLE
Clarify that any CA that is included / chains to Mozilla Root store has to implement US sanction lists

### ISSUE THREAD

**Issue by RufusJWB** [mozilla/pkipolicy#174]
The comment https://groups.google.com/d/msg/mozilla.dev.security.policy/nnLVNfqgz7g/UfzEiBI2CAAJ indicates to me, that it is the intended business model of DarkMatters to sell publicly trusted certificates to individuals or companies that are under US (or EU) sanctions. Since Mozilla is a foundation under US jurisdiction I would propose to make clear in the Root Store Policies that this is a banned behavior which leads ultimately to the revocation of the CA.

**Comment by dzacharo** [comment]
CAs must obey the laws and rules of their own jurisdiction. If a CA is operating in the jurisdiction of the US then these laws apply (including the US sanctions). If a CA is operating outside the US jurisdiction, is your suggestion that the CA must follow US legislation because Mozilla is founded in the US?

**Comment by RufusJWB** [comment]
> CAs must obey the laws and rules of their own jurisdiction. If a CA is operating in the jurisdiction of the US then these laws apply (including the US sanctions). 

Obviously. Also every CA operating in the EU have to follow the EU sanction lists, every CA operating in Russia has to follow Russian lists, and so on.

> If a CA is operating outside the US jurisdiction, is your suggestion that the CA must follow US legislation because Mozilla is founded in the US?

Yes, I think so. I'm not a lawyer, but as all CAs are chaining up to a Root under US jurisdiction, I would assume that they have to follow US law.

**Comment by dzacharo** [comment]
The Root is under the CA's Jurisdiction. Your suggestion sounds very confusing, at least to me.

**Comment by sleevi** [comment]
I think it best not to speculate on legal matters in these issues, and I’m
not sure this bug is actionable. I would actually recommend closing this.
