### ISSUE TITLE
Forbidden Practices wiki page says email validation cannot be delegated to 3rd parties

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#175]
https://wiki.mozilla.org/CA/Forbidden_or_Problematic_Practices
"Delegation of Domain / Email Validation to Third Parties
This is forbidden by the Baseline Requirements, section 1.3.2.
Domain and Email validation are core requirements of the Mozilla's Root Store Policy and should always be incorporated into the issuing CA's procedures. Delegating this function to 3rd parties is not permitted."

Some CAs have been pointing folks to this section in the wiki page, so we should have a discussion about it in m.d.s.p to determine whether to update the wiki page to remove the email validation part from this section, or to add this rule to our root store policy.

**Comment by wthayer** [comment]
@WilsonKathleen is the question here about S/MIME certificates? I can understand why there would be some confusion about the delegation of email address validation in S/MIME certificates to 3rd parties, especially if the intermediate is name constrained. A quick search of the m.d.s.p. archives didn't produce any hits that explain the intent of this requirement.

**Comment by WilsonKathleen** [comment]
> @WilsonKathleen is the question here about S/MIME certificates? 

Yes
