### ISSUE TITLE
Clarify revocation requirements for intermediate certificates in regards to ca-compliance bugs

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#177]
Section 6, Revocation, of Mozilla's Root Store Policy says:
"CAs MUST revoke Certificates that they have issued upon the occurrence of any event listed in the appropriate subsection of section 4.9.1 of the Baseline Requirements, according to the timeline defined therein."

Section 4.9.1.2 of the BRs says: "The Issuing CA SHALL revoke a Subordinate CA Certificate within seven (7) days if one or more of the following occurs: ...
5. The Issuing CA is made aware that the Certificate was not issued in accordance with ... this document"

This seems to imply that an intermediate certificate that was not issued in full accordance with the rules of the BRs must be revoked within 7 days of the CA becoming aware of any non-compliance with the BRs. However, I do not believe that was the intent, and I think this should not apply to intermediate certs that only issue non-SSL certs.

This issue is about fully considering the implications for intermediate certificates, and clarifying Mozilla's root store policy to better reflect our expectations.

**Comment by wthayer** [comment]
@WilsonKathleen I'm not clear on what you are suggesting here. The applicability of the BRs to non-TLS intermediates is issue #176 Our revocation guidance applies to EE and intermediate certificates. Are you suggesting that we go further and explicitly override the requirements on BR section 4.9.1.2 in policy? If so, would we simply exempt CAs from following that section of the BRs?

**Comment by WilsonKathleen** [comment]
This particular issue is about considering the impact of Mozilla's root store policy on intermediate certs that have EKU preventing them from issuing TLS certs.
