### ISSUE TITLE
Sunset SHA-1 in S/MIME Certificates

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#178]
Consider setting a date after which SHA-1 S/MIME certificates may no longer be issued.

**Comment by BenWilson-Mozilla** [comment]
This would be an edit to MRSP [section 5.1.3](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#513-sha-1). The entire section should probably be reworded. When should SHA1 still be allowed? Where is it still being used effectively/securely?

**Comment by BenWilson-Mozilla** [comment]
What if the language were deleted and replaced with "CAs SHALL NOT sign SHA-1 hashes over end-entity certificates that chain up to roots in Mozilla's program unless the end-entity certificate is an OCSP signing certificate or has an EKU extension that does not contain the id-kp-serverAuth, id-kp-emailProtection, or anyExtendedKeyUsage key purpose"?

**Comment by sleevi** [comment]
Was that meant to say “or unless the CA had an EKU …”?

allowing signing of SHA-1 “blobs” by a CA - whether certificate, OCSP response, or other - is the issue. So you don’t want the rule to be on end-entity, you want it to be based on the use of key.

Practically, though, there’s compelling reason to have no exceptions, given how even in 2021, we still saw CAs thinking SHA-1 signing was permissible (although we never found out what part of the language was unclear)

**Comment by BenWilson-Mozilla** [comment]
What if [MRSP 5.1.3](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#513-sha-1) was replaced in its entirety to say, "Effective [date], CAs SHALL NOT sign SHA-1 hashes over certificates, CRLs, or OCSP responses, unless the corresponding CA certificate has an EKU extension that does not contain the id-kp-serverAuth, id-kp-emailProtection, or anyExtendedKeyUsage key purpose."  ?

**Comment by sleevi** [comment]
I would remove the “unless” entirely - as it is just trying to capture CAs that are out of scope for Mozilla Policy, which the Mozilla Policy scope already addresses.

the reason being is it can still lead to misinterpretations - such as “what if I have (one of the listed key purposes) and (some unrelated purpose)”

**Comment by CBonnell** [comment]
> What if [MRSP 5.1.3](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#513-sha-1) was replaced in its entirety to say, "Effective [date], CAs SHALL NOT sign SHA-1 hashes over certificates, CRLs, or OCSP responses, unless the CA certificate corresponding to the signing key has an EKU extension that does not contain the id-kp-serverAuth, id-kp-emailProtection, or anyExtendedKeyUsage key purpose." ?

If we want to specify a complete ban on SHA-1 signing, I suggest removing 5.1.3 in its entirety and amending 5.1.1 to remove the "RSASSA-PKCS1-v1_5 with SHA-1". I plan to propose a follow-up ballot to the SHA-1 OCSP signing ballot (SC53) that will entirely remove the "RSASSA‐PKCS1‐v1_5 with SHA‐1" option in BR section 7.1.3.2.1, achieving the same effect in the BRs.

I do want to note that I did a quick scan of WebPKI ARLs and saw that there are a dozen or so CAs using SHA-1 for CRL signing. Given that there is virtually no attacker-controlled data in a tbsCertificateList, I believe the level of risk is much lower for SHA-1 CRL signing than it is for OCSP signing (where arbitrary attacker-supplied data in the nonce is signed). It is for this reason that I'm proposing sunsetting OCSP SHA-1 signing earlier than the other data types in the BRs. Perhaps Mozilla would want to consider a similar approach here.

**Comment by BenWilson-Mozilla** [comment]
@CBonnell  - Hi Corey - could you send me the search you used or the results so that I can see the scope of the SHA1 CRL signing still taking place?  Thanks, Ben

**Comment by CBonnell** [comment]
@BenWilson-Mozilla, here's the list of ARLs: https://gist.github.com/CBonnell/e4f2a601c3e94649a2bd2bca5c4676ff.

**Comment by BenWilson-Mozilla** [comment]
Thanks.  The list contains 30 CDPs for 19 unique CRLs issued by 13 CA operators. Because these are ARLs, the list doesn't appear to include CRLs for Issuing CAs, which are likely many more.  I'm wondering whether we could have 3 SHA1 sunset dates?
1 - end entity (SMIME) certificates
2 - ARLs
3 - CRLs
Does anyone have any suggestions for such sunset dates?

**Comment by BenWilson-Mozilla** [comment]
See discussion https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/CnVjV-bFcyI/m/TFuWOy2BAwAJ
