### ISSUE TITLE
Require Incident Reports be submitted via Bugzilla

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#181]
@sleevi stated:

One thing to consider with such a policy is whether to formalize the use of Bugzilla to track these. In looking through incident reports that have been filed, we see a fair distribution between the initial reporting being on the email list vs Bugzilla. We've certainly seen Bugzilla be more useful in tracking unacknowledged questions and responses (via the use of Needs-Info). Would it make sense to require that the incident report be provided via Bugzilla, with a notification to the mail list?

and:

My concern is that there have been several high-profile incidents which have been discussed in m.d.s.p., in which very relevant questions from members of the community go ignored, perhaps deliberately, and it becomes difficult to track in all of the discussion what those points were. However, I suppose the same issue may similarly exist if tracking the discussion through Bugzilla. This suggestion may end up being orthogonal to the policy update question, but it's one largely motivated by wanting to either make sure CAs are aware of the need to respond to questions - or to make sure that it's accurately noted when CAs ignore or otherwise fail to do so.

I believe this proposal should be coupled with a mechanism for automatically publishing new incident bugs to the m.d.s.p. list so that the community - many of whom do not regularly monitor Bugzilla - are informed of the status of incident bugs.

**Comment by BenWilson-Mozilla** [comment]
I think this issue can be closed because it is now well-established in policy and practice that all incidents must be filed in Bugzilla.
