### ISSUE TITLE
Require disclosure of incidents in Audit Reports

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#187]
Reference: https://groups.google.com/d/msg/mozilla.dev.security.policy/4Co_3FZxfLA/tNOXK1FAAAAJ

Consider requiring audit reports to list all incidents that occurred during the audit period (or clearly state that the auditor is not aware of any)

**Comment by BenWilson-Mozilla** [comment]
Many auditors are doing this already.  Does anyone have a reference I can look at to learn more about why?  Currently https://wiki.mozilla.org/CA/Responding_To_An_Incident says "The issue will need to be listed as a finding in your CA’s next BR audit statement."  But that is for delayed revocation.  [Section 2.4 of Mozilla Root Store Policy](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#24-incidents) (Incidents), currently doesn't say anything, but I'm thinking language could be added there.

**Comment by BenWilson-Mozilla** [comment]
I am thinking that section 3.1.4 of the Mozilla Root Store Policy would be where to place this requirement.
