### ISSUE TITLE
Require disclosure of jursidictionOfIncorporation data sources

### ISSUE THREAD

**Issue by sleevi** [mozilla/pkipolicy#188]
@GreatAmus recently shared on https://www.mail-archive.com/dev-security-policy@lists.mozilla.org/msg12547.html that DigiCert has begun publishing the list of data sources it uses for the EV certificate jurisdictionOfIncorporation, to ensure transparency, reuse, as well as compliance with the applicable EV Guidelines.

Much like problem reporting e-mails, this seems a great thing to standardize and require for all CAs. A possible transition plan may be initially to include within a CA Communication, and later (or concurrently) mandate disclosure in the CP/CPS (potentially as an Appendix or related resource)

**Comment by BenWilson-Mozilla** [comment]
Should this issue be closed or does its scope need to be expanded beyond EV? It seems that EV-issuing CAs are still recognizing that they need to disclose their data sources in line with the SCWG's Ballot SC30 and EVG sec. 11.1.3.

**Comment by BenWilson-Mozilla** [comment]
Closing this issue because rather than expanding its scope and adding something to the Mozilla Root Store Policy, it should be taken up by the CA/Browser Forum to improve the quality of OV TLS and S/MIME certificates.
