### ISSUE TITLE
Require information about auditor qualifications in the audit report

### ISSUE THREAD

**Issue by sleevi** [mozilla/pkipolicy#192]
Section 3.1.4 "Public Audit Information" of the Mozilla Root Store Policy requires a variety of disclosures about the parameters and scope of the audit, above and beyond what the Baseline Requirements require.

While it requires the disclosure of the name and address of the organization performing the audit, it does not provide disclosure about the auditors involved, such as their professional experience or relevant qualifications.

The [US Federal PKI approach](https://www.idmanagement.gov/community/twg/fpki-cas-audit-info/) may provide a model that is useful and relevant to ensuring the proper disclosures, and would be in line with [Mozilla Root Store Policy v1.0](https://wiki.mozilla.org/CA:CertificatePolicyV1.0) definition of "competent party". That version of the policy required _public information_ regarding the auditor's:
> * knowledge of CA-related technical issues such as public key cryptography and related standards;
> * experience in performing security-related audits, evaluations, or risk analyses; and
> * honesty and objectivity.

In the [current version](https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-annual-review-requirements.pdf) of the FPKI audit requirements, something similar is required, as captured in [Appendix B-1](https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-annual-review-requirements.pdf#page=16), in the requirements for "Auditor Background Information", and [Appendix C](https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-annual-review-requirements.pdf#page=21) with respect to Auditor Guidance.

You can see how this practically works by examining a US Federal PKI audit, such as for the [Government Publishing Office](https://www.oversight.gov/report/gpo/federal-pki-compliance-report-1), [Exhibit 1](https://www.oversight.gov/sites/default/files/oig-reports/Assessment%20Report%2019-12%20GPO%20Federal%20PKI%20Compliance_0.pdf#page=9). 

With the exceptions of PIV-specific references, Appendix C could be largely adopted as a model for clarifying the policy expectations (e.g. as a wiki page that can demonstrate the means of meeting the policy requirements), while to Section 3.1.4 of the Policy document, the four requirements from Appendix B-2 regarding "Auditor Background Information" could be added to capture the requirements, namely:

* Identity of the Auditor(s) and the individuals performing the audit
* Competence of the Auditor(s) to perform compliance audits as required by the applicable CP and CPS.
* Experience of the individuals performing the audit in auditing PKI systems as required by the applicable CP and CPS.
* Relationship of the Auditor(s) to the participating PKI and the organization operating the component(s) being audited. This relationship must clearly demonstrate the independence of the Auditor(s) as required by the applicable CP and CPS

**Comment by BenWilson-Mozilla** [comment]
As noted, this would need to mesh with section 8.2 of the Baseline Requirements. Language could be added to [section 3.2 of the Mozilla Root Store Policy](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#32-auditors).
