### ISSUE TITLE
Clarify S/MIME Validation practices for domains controlled by the CA or an Affiliate

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#196]
In [this m.d.s.p. thread](https://groups.google.com/d/msg/mozilla.dev.security.policy/xlqsq14HncI/XwaspUkaAQAJ), Rufus Buschart proposed the following clarification to section 2.2(2):

Maybe the following could be a reasonable rewording of the paragraph that makes the intention of the discussion clear, but isn't to 'clunky':

For a certificate capable of being used for digitally signing or encrypting email messages, the CA SHALL validate that the Applicant Representative (as defined in the BRGs) of the request controls the email account associated with the email address referenced in the certificate, except when the CA and the owner of the domain are Affiliates (as defined in the BRGs). The CA SHALL NOT delegate the validation of an email address. The CA's CP/CPS must clearly specify the procedure(s) that the CA employs to perform this validation.

With this wording we would reach:

1) The request can be initiated by the Applicant or Applicant Representative - due to the definition of Applicant Representative in the BRGs
2) Every CA can continue to issue S/MIME certificates as long as they perform a validation of the control of the email address
3) The CA cannot delegate the validation process
4) If the operator of the mail server operates its own CA, he doesn't have to perform error prone email address validations
5) We don't mix the words validation and verification for the same activity

Note: this does not include the policy 2.7 language that forbids delegation only of the domain component of the email address.

**Comment by dzacharo** [comment]
@wthayer, I am uncertain about 3, as it was fixed in #175 and in https://github.com/mozilla/pkipolicy/commit/85ae5a1b37ca8e5138d56296963195c3c7dec85a. According to the discussion on the email thread, I believe the consensus was that the CA cannot delegate the validation process *of the domain part*. Is the plan to disallow delegating the validation of the local part as well?

**Comment by sleevi** [comment]
That was specifically discussed on the thread, possible options explored,
and this language adopted.

**Comment by dzacharo** [comment]
I'm not sure if the clarifications described in this issue #196 are going to change the current proposal of https://github.com/mozilla/pkipolicy/commit/85ae5a1b37ca8e5138d56296963195c3c7dec85a which is why I asked.

I also find these clarifications problematic.

**Comment by sleevi** [comment]
And that’s explicitly stated here:
> Note: this does not include the policy 2.7 language that forbids delegation only of the domain component of the email address.

This issue tracks adopting a more restrictive, safer policy, but whose construct is difficult to get correct and thus doesn’t need to be resolved for Policy 2.7

**Comment by BenWilson-Mozilla** [comment]
I believe that section 2.2.2 of the Policy already covers most of the requested objectives. If not, somebody can raise them here again more clearly (while we leave this issue on the back burner). Maybe some better language will be proposed by the CA/Browser Forum's to-be-established S/MIME Working Group?

**Comment by RufusJWB** [comment]
Sorry, I haven't seen this thread before, since I wasn't at-mentioned in it.

My basic concern was, that we as a corporate PKI can't reasonably validate 350k email adresses - which are hosted by our own Exchange team - if a manual step needs to be performed. But with the language from the root store policy

> _or_ has been authorized by the email account holder to act on the account holder’s behalf

we could validate this once centrally and then continue to issue S/MIME certificates. So I'm fine with it.

**Comment by BenWilson-Mozilla** [comment]
Can this issue be closed?  Or should it be reopened as another issue or refocused on remaining challenges for enterprise implementations?  I don't see an issue here that can be referred to the CABF's SMIME WG for continued discussion unless it's rephrased.

**Comment by RufusJWB** [comment]
I think you can close this issue. I'll take care within the S/MIME WG that this special problem is taken into consideration.
