### ISSUE TITLE
Outline Policy Update Process

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#198]
In section 1.2 we reference policy changes. The process is described at https://wiki.mozilla.org/CA/Updating_Root_Store_Policy

Clarify this in the policy by adding a statement such as "This policy will be updated periodically. CAs MUST adhere to the current version."

**Comment by BenWilson-Mozilla** [comment]
What about putting that language at the bottom of section 1.1?  It could state, "This policy will be updated periodically in accordance with the Process for Updating the Root Store Policy [linked]. CAs MUST adhere to the current version of this policy."
