### ISSUE TITLE
Forbid SHA-1 Signatures on OCSP Responses

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#201]
Remove the following exception for SHA-1 signatures and forbid them completely on OCSP responses.

CAs MAY sign SHA-1 hashes over OCSP responses only if the signing certificate contains an EKU extension which contains only the id-kp-ocspSigning EKU

**Comment by BenWilson-Mozilla** [comment]
For reference - Section 7.1.3.2.1 of BR version 1.8 says, 

If used within an OCSP response, such as the signatureAlgorithm of a BasicOCSPResponse:
• All unexpired, un‐revoked Certificates that contain the Public Key of the CA Key Pair and that have the same Subject Name MUST also contain an extKeyUsage extension with the only key usage present being the id‐kp‐ocspSigning (OID: 1.3.6.1.5.5.7.3.9) key usage.

Also, see Issue #178.

**Comment by CBonnell** [comment]
Given that there is a proposal in servercert-wg to ban this at the BR level (https://github.com/cabforum/servercert/pull/330), does anything further need to be changed in Mozilla policy?

**Comment by briansmith** [comment]
> CAs MAY sign SHA-1 hashes over OCSP responses only if the signing certificate contains an EKU extension which contains only the id-kp-ocspSigning EKU

IMO the issue shouldn't be whether the CA is allowed to sign OCSP responses with SHA-1; it is fine for them to create OCSP responses that are signed with SHA-1. The important thing is that they must always respond to an OCSP request that indicates support for SHA-{256,384} with a certificate signed with the indicated algorithm. That is, it should be OK for a CA to create a SHA-1 signed OCSP response for backward compatibility and use it for legacy clients, and to create a SHA-256 (or SHA-384) signed response for modern clients.

**Comment by sleevi** [comment]
> That is, it should be OK for a CA to create a SHA-1 signed OCSP response for backward compatibility and use it for legacy clients,

not with nonces. This is where generally forbidding seems fine, especially to avoid edge cases of misinterpretations.

**Comment by CBonnell** [comment]
> > That is, it should be OK for a CA to create a SHA-1 signed OCSP response for backward compatibility and use it for legacy clients,
> 
> not with nonces. This is where generally forbidding seems fine, especially to avoid edge cases of misinterpretations.

Yes, this. The impetus for drafting my "sunset SHA-1 OCSP signing" ballot in the CABF was seeing that there are several OCSP responders in the WebPKI that perform on-demand SHA-1 signing and include the client-supplied nonce in the response. Signing arbitrary attacker-supplied content is a much greater risk than SHA-1 signing for subCAs or CRLs at this point, so the best approach here is to ban SHA-1 for OCSP altogether so we don't need to reason about what size nonces are safe, etc.

Additionally, as an interesting side note, some responders by default serve OCSP responses signed with rsaEncryptionWithSha256/384/512 but will also sign and return SHA-1 responses if the client explicitly requests rsaEncryptionWithSha1 in the PreferredSignatureAlgorithm OCSP request extension.

**Comment by briansmith** [comment]
In general I am happy to see use of SHA-1 go away so I'm not going to argue too hard. I think it would be good to address all of the issues (Don't return a cached response that wouldn't match the same nonce and algorithms that would be used for a non-cached response, always use a better algorithm when the request indicates support for a mutually-agreed better algorithm, never return a nonce in a response that doesn't match the nonce used in the request, etc.), rather than focus on a special case of SHA-1. That way when the same happens for SHA-256 everything already works.

**Comment by BenWilson-Mozilla** [comment]
So, is there some agreement that a more aggressive approach should be taken to remove SHA1?  Would it be appropriate to join this issue with Issue #178, adopt a policy this year (2022) and set a deadline for this to happen? If so, when?

**Comment by BenWilson-Mozilla** [comment]
See discussion https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/CnVjV-bFcyI/m/TFuWOy2BAwAJ

**Comment by BenWilson-Mozilla** [comment]
Closing this as MRSP section 5.1.3 states, that as of July 1, 2023, "CAs SHALL NOT sign SHA-1 hashes over: ... OCSP responses".
