### ISSUE TITLE
Require CAs to publish accepted methods for proving key compromise

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#205]
DIscussion: https://groups.google.com/d/msg/mozilla.dev.security.policy/DeztURyCHPo/1IZnDsMuAQAJ

In this thread, a few ideas for standardizing a mechanism for proving key compromise to a CA were proposed (RFC 8555, ACME). It was also proposed that Mozilla simply require CAs to disclose their acceptable methods in the CPS, section 4.9.12, "Special Requirements for
Key Compromise"

**Comment by mpalmer** [comment]
If it helps, there is now an open-source ACME server which is designed for the sole purpose of receiving revocations: https://github.com/tobermorytech/acmevoke.

**Comment by BenWilson-Mozilla** [comment]
Section 4.9.3 of the Baseline Requirements says, "The CA SHALL provide Subscribers, Relying Parties, Application Software Suppliers, and other third parties with clear instructions for reporting suspected Private Key Compromise, Certificate misuse, or other types of fraud, compromise, misuse, inappropriate conduct, or any other matter related to Certificates. The CA SHALL publicly disclose the instructions through a readily accessible online means and in section 1.5.2 of their CPS."  But I suppose we can require CAs to specify the allowed methods of demonstrating key compromise in section 4.9.12 of their CPSes.  In which section of the Mozilla Root Store Policy should we add this language?  What about as a new fourth paragraph in section 6, Revocation?
