### ISSUE TITLE
Require all OCSP responses to have a nextUpdate field

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#21]
Add a requirement that every OCSP response must have a nextUpdate field. This is required to ensure that OCSP stapling works reliably with all (at least most) server and client products.

**Comment by gerv** [comment]
Proposal: update the second bullet in point 3 of the Maintenance section so that the last sentence reads:

<blockquote>
OCSP responses from this service must have a defined value in the nextUpdate field, and it must be less than ten days after the response was signed.
</blockquote>

**Comment by briansmith** [comment]
The time the response was signed is `producedAt`. However, the period of time that you want is `nextUpdate` - `thisUpdate`. Therefore s/the response was signed/the thisUpdate field/.

Also, I suggest s/less than ten days/no more than ten days/; in particular, it should be allowed to be exactly 10 days.

**Comment by gerv** [comment]
New draft:

> OCSP responses from this service must have a defined value in the nextUpdate field, and it must be no more than ten days after the thisUpdate field.
