### ISSUE TITLE
Align OCSP requirements in Mozilla's policy with the BRs

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#211]
The CA/Browser Forum is currently discussing the draft "Browser Alignment" ballot (https://github.com/sleevi/cabforum-docs/pull/10) which includes adding the following text. We should consider updating section 6 of Mozilla's Root Store Policy along these lines.

May be added to section 4.9.10 of the BRs:
“The validity interval of an OCSP response is the difference in time between the thisUpdate and nextUpdate field, inclusive. For purposes of computing differences, a difference of 3,600 seconds shall be equal to one hour, and a difference of 86,400 seconds shall be equal to one day, ignoring leap-seconds.
For the status of Subscriber Certificates:
1. OCSP responses MUST have a validity interval greater than or equal to eight hours;
2. OCSP responses MUST have a validity interval less than seven days;
3. For OCSP responses whose validity interval is less than or equal to sixteen hours, the CA SHALL update the information provided via an Online Certificate Status Protocol at least eight hours prior to the nextUpdate;
4. For OCSP responses whose validity interval is greater than sixteen hours, the CA SHALL update the information provided via an Online Certificate Status Protocol prior to one-half of the validity period remaining before the nextUpdate.”

May be added to section 7.1.2.3(c, authorityInformationAccess) of the BRs:
“This extension MUST be present. It MUST NOT be marked critical, and it MUST contain the HTTP URL of the Issuing CA's OCSP responder (accessMethod = 1.3.6.1.5.5.7.48.1). It SHOULD also contain the HTTP URL of the Issuing CA's certificate (accessMethod = 1.3.6.1.5.5.7.48.2).”

**Comment by dzacharo** [comment]
The current BRs say in 4.9.10:

> "The CA SHALL update information provided via an Online Certificate Status Protocol at least every four days. OCSP responses from this service MUST have a maximum expiration time of ten days."

I believe the update to "OCSP responses MUST have a validity interval less than seven days;" may create confusion in the existing implementations that set the next update to "7 days". I hope an additional second will not be considered a violation, but if it is, then I recommend updating the proposed requirement to align with the existing language.

**Comment by sleevi** [comment]
@dzacharo Yeah, I'm still working out with Microsoft some possible changes to their root program on https://github.com/sleevi/cabforum-docs/pull/18 that would address https://github.com/mozilla/pkipolicy/issues/211#issuecomment-626864849

**Comment by WilsonKathleen** [comment]
Note that the draft Browser Alignment ballot has been updated...
https://github.com/sleevi/cabforum-docs/pull/10/files
2. OCSP responses MUST have a validity interval less than or equal to ten days;

**Comment by BenWilson-Mozilla** [comment]
Closing this as MRSP section 6 is consistent with section 4.9.10 of version 1.7.1 of the CA/Browser Forum's Baseline Requirements - https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.1-redlined.pdf.

**Comment by WilsonKathleen** [comment]
I see that MRSP section 6 is consistent with this part of the BRs: "Prior to 2020-09-30: The CA SHALL update information provided via an Online Certificate Status Protocol at least every four days. OCSP responses from this service MUST have a maximum expiration time of ten days."

MRSP section 6 doesn't specify all of the new BR language as follows, but maybe MRSP doesn't need to include all of the detail.
"Effective 2020-09-30:
1.OCSP responses MUST have a validity interval greater than or equal to eight hours;
2.OCSP responses MUST have a validity interval less than or equal to ten days;
3.For OCSP responses with validity intervals less than sixteen hours, then the CA SHALL update the information provided via an Online Certificate Status Protocol prior to one-half of the validity period before the nextUpdate.
4.For OCSP responses with validity intervals greater than or equal to sixteen hours, then the CA SHALL update the information provided via an Online Certificate Status Protocol at least eight hours prior to the nextUpdate, and no later than four days after the thisUpdate."

Might be worthwhile to raise the question in mozilla.dev.security.policy about if we should add more/similar detail to section  6 of MRSP.

**Comment by BenWilson-Mozilla** [comment]
I'm going to close this issue based on a conclusion that Mozilla requirements do not conflict with the Baseline Requirements and provide independent requirements for OCSP services for SMIME certificates.
