### ISSUE TITLE
Require at least one CABF defined-policy OID in certificatePolicies extension for TLS certs

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#212]
The CA/Browser Forum is currently discussing the draft "Browser Alignment" ballot (https://github.com/sleevi/cabforum-docs/pull/10) which includes adding the following text. We should consider updating Mozilla's Root Store Policy along these lines if this item does not get added directly to the BRs.

May be added to section 7.1.6.4 of the BRs:
“A Certificate issued to a Subscriber MUST contain, within the Certificate's certificatePolicies extension, one or more policy identifier(s) that are specified beneath the CA/Browser Forum's reserved policy OID arc of {joint-iso-itu-t(2) international-organizations(23) ca-browser-forum(140) certificate-policies(1)} (2.23.140.1).”

**Comment by BenWilson-Mozilla** [comment]
If this change is not made in the Baseline Requirements, then we would need to figure out where to add it as a new section in Mozilla Root Store Policy.  Microsoft's language could be used as a model:

"CAs must declare one of the following policy OIDs in its Certificate Policy extension end-entity certificate:

    DV 2.23.140.1.2.1
    OV 2.23.140.1.2.2
    EV 2.23.140.1.1.
    IV 2.23.140.1.2.3
    EV Code Signing 2.23.140.1.3
    Non-EV Code Signing 2.23.140.1.4.1"

**Comment by BenWilson-Mozilla** [comment]
Section 7.1.6.4 (Subscriber Certificates) of version 1.7.1 of the Baseline Requirements (https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.1-redlined.pdf) now states, 
"Effective 2020-09-30, a Certificate issued to a Subscriber MUST contain, within the Certificate’s certificatePolicies extension, one or more policy identifier(s) that are specified beneath the CA/Browser Forum’s reserved policy OID arc of {joint-iso-itu-t(2) international-organizations(23) ca-browser-forum(140) certificate-policies(1)} (2.23.140.1).

I suggest we close this issue as appropriately resolved.
