### ISSUE TITLE
Remove note about Firefox not supporting RSA-PSS

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#217]
When [Bug #1088140](https://bugzilla.mozilla.org/show_bug.cgi?id=1088140) is fixed, remove the following sentence from section 5.1.1:
"Note: as of version 70, RSASSA-PSS encodings are not supported by Firefox."

**Comment by BenWilson-Mozilla** [comment]
Note:  Apparently (not verified) RSASSA-PSS encodings work with Root CA certificates, but this has not been tested with a certificate chain.

**Comment by defacto64** [comment]
However, the BR forbid RSASSA-PSS, so it seems impossible to perform a test using real (trusted) and BR-compliant TLS certs:

```
7.1.3.1.1 RSA
The CA SHALL indicate an RSA key using the rsaEncryption (OID: 1.2.840.113549.1.1.1)
algorithm identifier. The parameters MUST be present, and MUST be an explicit NULL.
The CA SHALL NOT use a different algorithm, such as the id‐RSASSA‐PSS (OID:
1.2.840.113549.1.1.10) algorithm identifier, to indicate an RSA key.

```

**Comment by sleevi** [comment]
Adriano: I don’t understand your point? Ben’s remark was about new roots,
yours appears to be  existing roots?

And yea, PSS continues to be forbidden (and is not widely implemented in
NSS; presumably the “it works” is because signatures for roots aren’t
verified).

**Comment by defacto64** [comment]
Please ignore my comment, I was mistaken.

**Comment by BenWilson-Mozilla** [comment]
This has been fixed in MRSP v. 2.8.
