### ISSUE TITLE
Section 2.1.{6,7} indentation is wrong

### ISSUE THREAD

**Issue by mimi89999** [mozilla/pkipolicy#224]
Hello,
I noticed that indentation of sections 2.1.6 and 2.1.7 in https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#21-ca-operations is wrong.

**Comment by BenWilson-Mozilla** [comment]
Thanks!  I'll get that fixed right away.

**Comment by WilsonKathleen** [comment]
Fixed. Thanks for bringing this to our attention.
