### ISSUE TITLE
Add policy about old root certificates

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#232]
We should add policy about old root certificates, e.g.: 
1) Not accepting inclusion requests for root certificates created before a certain date.
2) CAs that currently have root certificates in our program that were created before a certain date should be migrated to newer root certificates.
The policy should give the overall guidance, and link to a wiki page with details.

Ben started discussion about this here:
https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/TII3OVNINEM/m/ysMqglFqFAAJ

**Comment by BenWilson-Mozilla** [comment]
Additional factors to creation date could be: expiry date, key size, trust bits, subCA quantity and characteristics (including number of CAs externally operated by third parties), key protection, audit history, and whether organization name in certificate matches current owner/operator.

**Comment by BenWilson-Mozilla** [comment]
See post here:  https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/PuI1ZILqZ7o/m/E-cKaw_jBAAJ

**Comment by BenWilson-Mozilla** [comment]
According to https://www.chromium.org/Home/chromium-security/root-ca-policy/, Chrome will have a future policy that may limit the root CA certificate use to 7 years, "measured from the initial date of certificate inclusion. ... CA operators would be encouraged to apply with a replacement CA certificate after 5 years of inclusion,...."  (Chrome also has a policy that key material must be generated within 5 years of application.) Maybe Mozilla could adopt similar wording that limits the usability of root CAs for TLS to something like 12 years (and, e.g., 20 years for S/MIME-enabled roots). The cadences for CA operators to file inclusion requests for replacement root certificates will likely be different among root store operators, as there are differences with root store processing times today. One of the underlying policy concerns is future-proofing CAs to account for increased computing capability, so there will need to be some type of "freshness" metric as well. These two ideas could be combined into one requirement that limits the use of roots for TLS to 15 years, as measured from the creation of key material. Or maybe it is better just to keep separate the currently-used metrics for various CA lifetime factors (e.g. key generation date, root submission date, CA certificate lifetime/expiration date, etc.)?

**Comment by BenWilson-Mozilla** [comment]
As mentioned here, https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/-qSvEhaHs1c/m/VUjfxK00AQAJ, 
the current thinking is that the policy should be revised to state as follows:

<html><body>
<div class="DTXlsb"><html-blob><div dir="ltr"><div>
<p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt"><span style="font-size:11pt;font-family:Arial;color:rgb(0,0,0);background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:underline;vertical-align:baseline;white-space:pre-wrap">Section 7.4 “Root CA Life Cycles”</span><span style="font-size:11pt;font-family:Arial;color:rgb(0,0,0);background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap"> </span></p></div></div></html-blob></div><html-blob><div dir="ltr"><div><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt"><span style="font-size:11pt;font-family:Arial;color:rgb(0,0,0);background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap">Root CA certificates included in the Mozilla root store will be distrusted when their CA key material is over 15 years old. The date of CA key material generation SHALL be determined by reference to the auditor’s key generation ceremony report. For key material generated before July 1, 2012, Mozilla will assume that the key material was generated on the “Valid From” date in the root CA certificate. For transition purposes, root CA certificates in the Mozilla root store will be distrusted according to the following schedule:  </span></p><div dir="ltr" style="margin-left:0pt" align="left">

Key Material Created | Distrust Date
-- | --
Before January 1, 2006 | April 15, 2025
2006-2007 | April 15, 2026
2008-2009 | April 15, 2027
2010-2011 | April 15, 2028
2012- April 14, 2014 | April 15, 2029
April 15, 2014 - present | 15 years from creation

</div><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt"><span style="font-size:11pt;font-family:Arial;color:rgb(0,0,0);background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap"><span style="font-size:11pt;font-family:Arial;color:rgb(0,0,0);background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap">This schedule is subject to change if the underlying algorithms become more susceptible to cryptanalytic attack.</span></span></p><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt"><span style="font-size:11pt;font-family:Arial;color:rgb(0,0,0);background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap">CA operators MUST apply to Mozilla for inclusion of their next generation root certificate at least 2 years before the Distrust Date above.</span></p></div></div></html-blob>
</body>
</html>

**Comment by BenWilson-Mozilla** [comment]
I've removed this from the branch for 2.8.1 - https://github.com/BenWilson-Mozilla/pkipolicy/commit/5cb82e40ed58c0d181cefedc43d03b3cc17fe79f
