### ISSUE TITLE
Require CCADB Disclosure of Full CRLs (or equivalent JSON array) for CRLite

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#235]
This item is about requiring CAs to fill in either the "Full CRL Issued By This CA" or the "JSON Array of Partitioned CRLs" field in the CCADB for intermediate certificates that are capable of issuing TLS certificates chaining up to root certificates in Mozilla's root store.

Mozilla is moving forward with [CRLite](https://blog.mozilla.org/security/2020/01/09/crlite-part-1-all-web-pki-revocations-compressed/), so we need to get full CRL information for TLS certificates.

CRLite currently determines the CRL URIs based on the certificates in CT, but the BRs do not require cRLDistributionPoints to be present in end-entity TLS certificates. So until the CAs are required to provide full CRLs (or JSON equivalent) in the CCADB and CRLite is updated to use those CRLs, CRLite will not know about **all** end-entity TLS certificate revocations. (reference: section 7.1.2.3 of the BRs)

**Comment by BenWilson-Mozilla** [comment]
Hi @WilsonKathleen, under this issue, are we wanting to collect the full CRL for root certificates as well, or is that just an Apple requirement? If the former, then would we need to collect the information and then populate it in the CCADB for root certificates? I was just working on language for section 4.1 of the MRSP, and I wasn't sure whether to include this as a requirement for roots with the websites trust bit. Thanks.

**Comment by BenWilson-Mozilla** [comment]
Public discussion has started on mdsp - https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oqpGt9LudnI/m/D4G12eSeBQAJ

**Comment by WilsonKathleen** [comment]
> Hi @WilsonKathleen, under this issue, are we wanting to collect the full CRL for root certificates as well

Hi @BenWilson-Mozilla, we currently only need full CRLs for the certificates that intermediate certificates issue that are capable of being used for TLS. (i.e. for CRLite)
