### ISSUE TITLE
Require annual submission of self-assessments

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [mozilla/pkipolicy#240]
CAs should be required to complete a compliance self-assessment on an annual basis.  This can be checked in conjunction with their annual audit review.  See https://wiki.mozilla.org/CA/Compliance_Self-Assessment

**Comment by vanbroup** [comment]
This seems to be a duplicate of #123

**Comment by BenWilson-Mozilla** [comment]
Duplicate of #123.
