### ISSUE TITLE
Requirement to disclose DCV method subsection should not be "SHOULD"

### ISSUE THREAD

**Issue by AGWA** [mozilla/pkipolicy#253]
Commit 86a7ff6ab4030591072de6fd7db9617673f52e3c replaced "should" with "SHOULD" in 2.2 (3) with regards to disclosing the BR subsection for DCV methods. This "should" was being treated as a requirement in numerous incidents (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1705480) in line with the English definition of "should".  However, "SHOULD" is a term of art from RFC 2119 and is explicitly not a requirement, meaning this change had the effect of removing a (rather useful) requirement.

Since this change wasn't discussed anywhere as best I can tell, I assume it is an accidental regression in the MRSP, and should be reverted immediately (or changed into "MUST").

**Comment by BenWilson-Mozilla** [comment]
Thank you for spotting this. I am surprised that a CA would incorrectly assume that it did not have to disclose its DCV methods.  I will make it a MUST, as you suggest.  I also noticed that somehow the other "must" in the sentence was not capitalized.  The revised sentence would read, "The CA operator's CPS (or, if applicable, the CP or CP/CPS) MUST clearly specify the procedure(s) that the CA employs, and each documented procedure MUST state which subsection of 3.2.2.4 it is complying with." FWIW, fields are being added to a future version of the CCADB for CAs to disclose which sections within BR 3.2.2.4 they are using.

**Comment by BenWilson-Mozilla** [comment]
Discussion of this was started in mdsp - https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/weG75ua51VM/m/8jwOeHw4CAAJ
