### ISSUE TITLE
Consider Requiring Logging in Certificate Transparency

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [mozilla/pkipolicy#255]
Consider updating Mozilla's Root Store Policy to require that TLS server certificates be logged using Certificate Transparency.

**Comment by robstradling** [comment]
@BenWilson-Mozilla It's worth noting that no other *Root Store Policy* requires TLS server certificates to be logged to CT logs.  Chrome and Apple both have separate CT Policies:
- The [Chrome CT Policy](https://github.com/GoogleChrome/CertificateTransparency/blob/master/ct_policy.md#:~:text=The%20issuance%20of%20certificates%20that%20are%20not%20CT%20compliant%20is%20not%20considered%20mis%2Dissuance%20or%20a%20violation%20of%20Chrome%E2%80%99s%20root%20program%3B%20such%20certificates%20will%20simply%20fail%20to%20validate%20in%20CT%2Denforcing%20versions%20of%20Chrome.) says:
*"The issuance of certificates that are not CT compliant is not considered mis-issuance or a violation of Chrome’s root program; such certificates will simply fail to validate in CT-enforcing versions of Chrome."*
- The [Apple CT Policy](https://support.apple.com/en-gb/HT205280) doesn't explicitly state the Apple's root program's view on CT non-compliance, but I think the intent was to mirror Chrome's approach.

**Comment by BenWilson-Mozilla** [comment]
I am going to close this issue because it is poorly worded.
