### ISSUE TITLE
Require separate intermediates for different usages (e.g. server auth, S/MIME)

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#26]
Mozilla should require separate intermediates for server certs, S/MIME, code signing etc., with each being technically constrained to issue only for that usage. This would reduce the risk from dodgy practices relating to non-server cert types. It also would mean that, for example, one could have different SHA-1 rules for different usages.

**Comment by RufusJWB** [comment]
Could you elaborate a little bit in detail, why you believe that it will `reduce the risk from dodgy practices` if one separates code signing and S/MIME? On a little bit abstract level both activities are the same: One signs the result of his work, be it an email or be it a piece of code.

Therefore I would even say it is worth pursuing to have both EKUs together in a certificate, especially since this would reduce the entry barrier for code signing which would increase the overall IT security.

**Comment by gerv** [comment]
Dimitris Zacharopoulos points out:

> Microsoft's Policy <https://social.technet.microsoft.com/wiki/contents/articles/31633.microsoft-trusted-root-program-requirements.aspx> currently says:

> "/New/ intermediate CA certificates under root certificates submitted for distribution by the Program must separate Server Authentication, S/MIME, Code Signing and Time Stamping uses. This means that a single intermediate issuing CA must not be used to issue both server authentication, S/MIME, and code signing certificates. A separate intermediate must be used for each use case."

**Comment by gerv** [comment]
@RufusJWB: well, a S/MIME cert's private key probably lives on a developer's desktop, as it needs to be accessible to their email program. I would hope the private key for a code signing cert is rather more well protected than that. Using the same cert for both leads to a lowest-common-denominator security.

**Comment by RufusJWB** [comment]
@gerv in the case of the [company](https://www.siemens.com/corp/en/index/digital_id.htm) I'm working for, the S/MIME cert's private keys of every employee (350 k world wide) and most of our external contractors are stored on a [smart card](https://bull.com/smart-card-solutions/) and can't be extracted. In our scenario it would make sense to have those EKUs together in one certificate but I understand that we are a exception with our PKI environment.

**Comment by RufusJWB** [comment]
@gerv In our case, the smart cards are holding one active authentication, one active encryption and up to 4 historic (either expired or revoked) encryption keys / certificates. The problem we have are related to our CA / RA software - the before mentioned configuration (2+4) is practically hard coded. So it would have been very attractive to simply add the code signing EKU to the authentication certificate. But now I understand, why this is not possible. Thank you!
