### ISSUE TITLE
Use language of capability throughout

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#27]
To standardise across the policy and be clear on what we mean, point 12 of the Maintenance section should change from language of intent to language of capability. So:

<blockquote>
CA operations and issuance of certificates to be used for SSL-enabled servers must also conform to version 1.3 or later of the CA/Browser Forum Baseline Requirements for the Issuance and Management of Publicly-Trusted Certificates.
</blockquote>

to

<blockquote>
CA operations relating to issuance of certificates capable of being used for SSL-enabled servers must also conform to version 1.3 or later of the CA/Browser Forum Baseline Requirements for the Issuance and Management of Publicly-Trusted Certificates.
</blockquote>

We should also change any other parts of the policy which don't make it clear that it's technical capability which is relevant when determining policy scope, not CA intent.

**Comment by gerv** [comment]
Inclusion section, bullet 7, has "to be used for" in several places, which needs to change to "capable of being used for" or equivalent. And we should define that capability, such that it matches what NSS recognises.

@kaie: can you tell us exactly how NSS decides a cert is usable for server auth? My understanding is that it is either:

* EKU present and id-kp-serverAuth present; or
* EKU not present

Is that correct? Do we recognise the anyEKU?

Can you say what the rule is for S/MIME? Is it the same as above but id-kp-emailProtection?

**Comment by kaie** [comment]
Answering will require reading the code.

**Comment by kaie** [comment]
I think you were hoping for a simple answer, but I'm afraid the answer is complicated.
I found an old document from 2002, where Nelson explains the requirements:
http://www-archive.mozilla.org/projects/security/pki/nss/tech-notes/tn3.html

**Comment by gerv** [comment]
@kaie: and you are sure that the answer from 2002 is still correct?

If so, thank you. That answer is far more than we need, but it shows us that currently, it either requires no EKU, or an EKU with id-kp-serverAuth. I've started a discussion in m.d.s.policy about whether we can tighten that up.

**Comment by kaie** [comment]
Gerv, two responses:
- I don't think the above code in NSS has been changed much, so I'd
  assume it's still mostly correct, but only asking around more widely would confirm
- note that you've asked about NSS. In the meantime, Firefox has switched to mozilla::pkix
  and its own certificate validation logic. I cannot say if Firefox has implemented the
  exact same rules.

**Comment by gerv** [comment]
@kaie: I guess I meant to ask about mozilla::pkix. Are you able to tell me how that works, or do I need to ask someone else?

**Comment by kaie** [comment]
I don't know how mozilla::pkix works.

**Comment by mozkeeler** [comment]
@gerv the second comment in this thread accurately describes how mozilla::pkix currently works (i.e. EKU present and id-kp-serverAuth present or EKU not present). anyEKU is not accepted in place of id-kp-serverAuth. If OCSPSigning is present, the certificate is not valid for serverAuth.

For S/MIME, it looks like the same logic but with id_kp_emailProtection, as you've noted.

**Comment by gerv** [comment]
Right. So we can use that to define what we mean by "capable" when fixing this bug.

Separately, we should work out whether we can drop the "EKU not present" branch of that test. See discussion in m.d.s.policy:
https://groups.google.com/forum/#!topic/mozilla.dev.security.policy/leZRiBJ4Vqs

**Comment by gerv** [comment]
I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1317245 on requiring id-kp-serverAuth.

**Comment by gerv** [comment]
So we should change to language of capability throughout, and define what "capable" means at first reference, with that definition being (for now) "id-kp-serverAuth or no EKU".
