### ISSUE TITLE
Write CCADB (Salesforce) Policy

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#31]
Following on from issue #9, I think we should have a separate document detailing how we want CAs to use the CCADB. As I understand it, much of this information is currently in various wiki pages. WilsonKathleen: can you list those pages, and give me some high-level guidance about how that information might be turned into a policy document?

**Comment by gerv** [comment]
(I've assigned this to you to give me that info, but you don't need to put the policy together.)

**Comment by WilsonKathleen** [comment]
CA instructions and responsibilities regarding the Common CA Database are here:
https://wiki.mozilla.org/CA:SalesforceCommunity
https://wiki.mozilla.org/CA:SalesforceCommunity#CA_Responsibilities

Here's a couple of other related wiki pages, in case this information also needs to be considered when writing the policy...

I started drafting a non-root-store specific wiki page here:
https://wiki.mozilla.org/CA:CommonCADatabase

There's a wiki page about root store operators participating in the CCADB here:
https://wiki.mozilla.org/CA:CommonCADatabase:RootStoreOperators

**Comment by gerv** [comment]
@WilsonKathleen: thanks for that. I think a CCADB policy would explain _what_ CAs were required to do, but the instructions on _how_ they do it (which might change more frequently than the "what") could remain on the wiki.

I think that, for flexibility, we need two documents - a common CCADB requirements, and a Mozilla-specific requirements. The Mozilla one may be very short, but it's good for us to have the flexibility to add requirements of our own, either because they are specific to our needs or because they have not yet been agreed by the group. Microsoft and others may have their own specific requirements too.

**Comment by gerv** [comment]
Closed by issue #9.
