### ISSUE TITLE
Solve the problem of audits for new subCAs

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#32]
We require subCAs to be immediately disclosed. We require audit information to be provided. But a newly-created subCA will not be covered by any audit. How to solve this problem?

A 4th HSM in a rack, alongside 3 identical ones, added for scaling, doesn't seem to require a new audit. A whole new infra with a whole new issuance process probably does. Where is the line, and how can we draw it clearly? And what documentation do we require for the first case, if anything?

See discussion at CAB Forum Meeting 39, and presentation from Peter Bowen.

**Comment by wthayer** [comment]
Minutes of the referenced discussion: https://cabforum.org/2016/10/19/2016-10-19-20-f2f-meeting-39-minutes/#Disclosure-of-Subordinate-CAs

This issue has been partially addressed with the requirement that audit statements list all CAs covered y the audit.
