### ISSUE TITLE
Add CC-0 license to policy

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#35]
CAs may want to copy bits of our policy into their working documents and other things; the best way to make that easy is to use CC-0.

**Comment by gerv** [comment]
This would involve adding a footer:

> Any copyright in this document is [dedicated to the Public Domain](http://creativecommons.org/publicdomain/zero/1.0/).

**Comment by sleevi** [comment]
As recommended on list, please review with your counsel, but CC0 may provide greater legal clarity.

**Comment by floatingatoll** [comment]
Note that the footer referenced above does not invoke CC0 in the manner indicated as authoritative by Creative Commons. They offer the following HTML block (replace One, Two, Three with the relevant words), of which the plain spoken language is:

> "To the extent possible under law, One <```https://two```> has waived all copyright and related or neighboring rights to Three. This work is published from: United States."

Full HTML (with really intense metadata attributes):

```
<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="https://licensebuttons.net/p/zero/1.0/80x15.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="https://two">
    <span property="dct:title">One</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">Three</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="US" about="https://two">
  United States</span>.
</p>
```

This is not intended as endorsement or support of any specific decision, but simply to record the variance.

**Comment by 1234-** [comment]
<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="http://www.google.se/sari.salmi386">
    <span property="dct:title">Sari Salmi</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">Mina sidor</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="SE" about="http://www.google.se/sari.salmi386">
  Sverige</span>.
</p>

**Comment by gerv** [comment]
@1234-: Er, this is not the right place to put that information if it relates to a work you are publishing.
