### ISSUE TITLE
Specify allowed PSS parameters

### ISSUE THREAD

**Issue by briansmith** [mozilla/pkipolicy#37]
I propose that the Mozilla policy 2.4 make explicit what PSS parameters are allowed in PSS signatures and PSS public keys. Specifically, I propose that we require that PSS signatures and PSS public keys contain `RSASSA-PSS-params` values: from the following set:

* { hashAlgorithm: sha256Identifier, maskGenAlgorithm: mgf1SHA256Identifier, saltLength: 32 }
* { hashAlgorithm: sha384Identifier, maskGenAlgorithm: mgf1SHA384Identifier, saltLength: 48 }
* { hashAlgorithm: sha512Identifier, maskGenAlgorithm: mgf1SHA512Identifier, saltLength: 64 }

This matching of parameters is what the TLS 1.3 protocol and other new IETF protocols require.

Also, as already specified in [RFC 4055](https://tools.ietf.org/html/rfc4055), the `trailerField` field must not be explicitly encoded, as the default value is the only acceptable value.

**Comment by tomato42** [comment]
I'd say that we should recommend against including parameters in EE certificate public key info structure. Inclusion of those parameters in EE certificate makes TLS 1.3 implementation more complex.

Secondly, saltLength has different interpretation in signature and in public key info. in the latter, it specifies the minimum salt length, not the only allowed one. What do we gain by excluding larger sizes? (I'm in favour of limiting the set of valid signatures that CA's can make, but policing signatures made by end users, in CMS or S/MIME, would be fruitless)

**Comment by sleevi** [comment]
@BenWilson-Mozilla I believe this can be closed out now? This was addressed by Mozilla Policy, and subsequently, the BRs.

**Comment by BenWilson-Mozilla** [comment]
This can be closed.
