### ISSUE TITLE
Specify allowed encoding of RSA PKCS#1 1.5 parameters

### ISSUE THREAD

**Issue by briansmith** [mozilla/pkipolicy#38]
I propose that Policy 2.4 explicitly specify the allowed encodings of RSA PKCS#1 1.5 AlgorithmIdentifiers in signatures and in public keys.

[RFC 4055](https://tools.ietf.org/html/rfc4055) already says "When any of these four object identifiers appears within an AlgorithmIdentifier, the parameters MUST be NULL." However, mozilla::pkix and possibly other implementations also accept the algorithm identifiers where the parameters are excluded. This is the only algorithm identifier for which we allow multiple encodings of the parameters, and it would be nice to have the code be able to enforce a canonical encoding. In particular, it would allow the code to compare algorithm identifiers using simple bytewise comparisons and completely avoid parsing them.

Presumably, the policy already requires implementations to conform to RFC 4055. It would be good for the policy to reiterate this conformance requirement and specifically emphasize the requirement that the `NULL` parameter MUST be encoded.

**Comment by gerv** [comment]
I'm putting this for consideration in 2.5, but we'd need to assess the webcompat risk of actually enforcing this, and check with CAs that there is no problem requiring things to be done this way.

**Comment by sleevi** [comment]
@BenWilson-Mozilla I believe this can be closed out now? This was addressed in Mozilla Policy, and later, the BRs.

**Comment by BenWilson-Mozilla** [comment]
This can be closed.
