### ISSUE TITLE
Policy about non-sequential audits

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#39]
The BRs state: "The period during which the CA issues Certificates SHALL be divided into an unbroken sequence of audit periods. An audit period MUST NOT exceed one year in duration." We track this data in the CCADB, but we should have a policy that says what the consequence should be whenever the rule is violated. 

See also #7.

**Comment by gerv** [comment]
@WilsonKathleen: what consequences do you suggest? Make them go back and get another audit to cover the gap?

**Comment by WilsonKathleen** [comment]
Yes, they should go back and get another audit to cover the gap. This  (no gaps in audit periods) should be required of all CAs, even if they only have the Email trust bit set.

As for the must not exceed one year duration, that's a BR-specific requirement, that I'm not too hung up on. Seems like if the CA needs to get have a longer audit period for some reason, then maybe they just need to let us know first.

**Comment by gerv** [comment]
The audit period is important because audits are retrospective. If a CA wants a 2-year audit, what they are really saying is "please can we go almost two years without anyone independently examining our processes?" 1 year is bad enough... 

Anyway, I'll look at whether we need to add any text about consequences or remediation.

**Comment by WilsonKathleen** [comment]
>> If a CA wants a 2-year audit, 

Totally agree. I was thinking more along the lines of 13 to 14 months, due to the auditor not being available, or xmas vacations...

**Comment by gerv** [comment]
CAs plan their audits significantly in advance; the auditor should make sure people are available, and not take the job. Also, the audit period (as you keep saying!) is not the same thing as the engagement period. The engagement period can be a little after if necessary. And if a CA has their cycle so they get audited over Christmas each year, they deserve everything they get... :-)

**Comment by gerv** [comment]
I think we can deal with this on a case-by-case basis rather than making policy. In most cases, we'll tell the CA to go back and get an audit covering the missing period, but not writing that down gives us the flexibility to ask for something else if we decide that's better. We already specify audit periods MUST be unbroken so if they aren't, we have scope to take action.
