### ISSUE TITLE
Replace all occurrences of 'CA' with "Certification Authority' when that is the intended meaning

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#40]
From https://bugzilla.mozilla.org/show_bug.cgi?id=669474#c4
""
... I still find inconsistent use of "CA".  
In particular, I see many instances of "CA hierarchy" where I cannot tell whether this is an organizational hierarchy (e.g., departments, divisions), a hierarchy of procedures, or a hierarchy of certificates.  This is a problem in "Mozilla CA Certificate Inclusion Policy", "CA:Recommended Practices", "CA:Problematic Practices", and possibly elsewhere.  
...
I suggest that "CA" be globally replaced with "certification authority" except in direct quotes of external sources (e.g., the CAB) and in titles of documents.  Then a careful reading would determine whether "CA" intended to refer to an organization or a certificate.  This would also resolve some of the lack of clarity about the phrase "CA hierarchy", where I suspect the proper phrase might be "certificate hierarchy".  

The problem to be addressed here is that both certification authorities and the end-using public both need some clarity and accuracy in order to understand Mozilla's process for approving the inclusion of root certificates.

**Comment by gerv** [comment]
The policy itself uses "CA" (or "issuing CA" or "subordinate CA") to refer to the organization and "CA certificate" to refer to the certificate fairly consistently. The two exceptions which need fixing are:

* Inclusion point 5 ("additional CAs")
* Inclusion point 18 ("CA hierarchy") x 2

So I think that fixing those two occurrences would be sufficient; we don't need a global expansion. Fixes to the wiki can be made by anyone, and are not tracked here :-)
