### ISSUE TITLE
Make clear that duplicate serial numbers are OK when supporting CT

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#41]
At least for RFC 6962 (-bis is a different issue), pre-certs are certs and so the duplication of (issuer name, serial number) between the pre-cert and the cert is technically a violation of Mozilla policy; we reserve the right not to include CAs who issue certs with "duplicate issuer names and serial numbers".

We should make it clear that this is OK in the CT case.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1016587

**Comment by gerv** [comment]
I propose the following change:

> duplicate issuer names and serial numbers;

->

> duplicate issuer names and serial numbers (except for in Certificate Transparency pre-certificates);

**Comment by briansmith** [comment]
Only a precertificate and the final (non-precertificate) certificate that corresponds to the precertificate are allowed to have the same serial number. This is much stricter than what you wrote. Your suggested text could be read as saying many things that aren't intended, such as that multiple precertificates are allowed to have the same serial number.

**Comment by gerv** [comment]
Fair point.

> duplicate issuer names and serial numbers (except that a Certificate Transparency pre-certificate is allowed to match the corresponding certificate);

**Comment by sleevi** [comment]
Alternatively, there's the language from BRs 7.1.2.5:
"For	purposes	of	clarification,	a	Precertificate,	as	described	in	RFC	6962	–	Certificate	Transparency,	shall	not	
be	considered	to	be	a	“certificate”	subject	to	the	requirements	of	RFC	5280	‐	Internet	X.509	Public	Key	
Infrastructure	Certificate	and	Certificate	Revocation	List	(CRL)	Profile	under	these	Baseline	Requirements"

**Comment by gerv** [comment]
Ryan: there are other requirements in our document which we want to apply to precertificates, so defining them as not certificates would have side-effects. So I'm going to go with the original limited exemption plan.

**Comment by briansmith** [comment]
Gervase Markham <notifications@github.com> wrote:

> Ryan: there are other requirements in our document which we want to apply
> to precertificates, so defining them as not certificates would have
> side-effects. So I'm going to go with the original limited exemption plan.


Note that in the -bis version, the precertificates are not syntactically
certificates, so that strategy probably won't work long-term.

Cheers,
Brian
-- 
https://briansmith.org/

**Comment by gerv** [comment]
When we actually do CT, we'll probably need to review the policy again (this is a bit of a band-aid, to deal with _other_ people doing CT), so thank you, let's keep that in mind for then.
