### ISSUE TITLE
New version of WebTrust BR Criteria -- v2.2

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#44]
From http://www.webtrust.org/principles-and-criteria/item83172 ...
Effective for audit periods starting on or after December 1, 2016.
Version 2.1 incorporates the CA/Browser requirements for the issuance and Management of Publicly-Trusted Certificates and Network and Certificate System Security requirements.  (See Appendices A, B, C and D in the Principles and Criteria document for more information). 
Version 2.1 incorporate two CA/Browser Forum requirements documents:
    Baseline Requirements for the Issuance and Management of Publicly-Trusted Certificates (“SSL Baseline Requirements”); and
    Network and Certificate System Security Requirements (“Network Security Requirements”)

The SSL Baseline Requirements are addressed in Principles 1, 2, and 3 of these audit criteria. The Network Security Requirements are addressed in Principle 4 of these audit criteria.

For audit periods starting prior to December 1, 2016, please continue to use WebTrust Principles and Criteria for Certification Authorities – SSL Baseline with Network Security – Version 2

**Comment by WilsonKathleen** [comment]
Note, added to v2.1: Principle 2, Criteria  Section 2.x –Reorganised to provide better clarity, including adding criterion for certificate serial number entropy (2.1), the SHA-1 sunset (2.10), and an explicit requirement of certificate conformance to RFC 5280 (2.6).

**Comment by gerv** [comment]
Exactly which version of the BRs do these refer to? See issue #30 for the complexities of requiring a new version of the BRs.

We don't _need_ to require 2.1 for all audits after Dec 1, 2016. We can require what we like. :-)

**Comment by WilsonKathleen** [comment]
New:
WEBTRUST PRINCIPLES AND CRITERIA FOR CERTIFICATION AUTHORITIES – SSL BASELINE WITH NETWORK SECURITY **Version 2.1** 
Release Date 1 November 2016 
Effective Date For audit periods commencing on or after 1 December 2016 
Based on the CA/Browser Forum Baseline Requirements for the Issuance and Management of Publicly - Trusted Certificates – **Version 1. 4.1**, and Network and Certificate Systems Security Requirements – Version 1.0

Previous:
WebTrust Principles and Criteria for Certification Authorities – SSL Baseline with Network Security – **Version 2.0**
RELEASE DATE April 3, 2014 
EFFECTIVE DATE Audit periods starting on or after July 1, 2014
Based on: CA/Browser Forum Baseline Requirements for the Issuance and Management of Publicly-Trusted Certificates – **Version 1.1.6** 
AND Network and Certificate Systems Security  Requirements – Version 1.0

**Comment by gerv** [comment]
So that's a problem, because 1.4.1 has IPR issues - it includes ballot 169. We can't move to requiring these audits (and therefore requiring people to use the IPR-uncertain domain validation methods) until all that is sorted out.

Gerv

**Comment by WilsonKathleen** [comment]
Please notice the version of the BRs that the previous (v2.0) WebTrust audit criteria used -- BR version 1.1.6. That's pre-SHA1 sunset rules, etc.

**Comment by gerv** [comment]
I agree continuing to use the old version is also problematic :-)

We discussed this on the CAB Forum call today. The point may be moot if some root programs require compliance with The 10 Methods anyway, but if Ballots 180 and 181 pass, Any Other Method will return to the BRs, and normal WebTrust auditor practice is to allow CAs to be compliant with a later version of the BRs than the one encoded, so they will be able to continue to use Any Other Method under a 2.1 audit anyway.

**Comment by gerv** [comment]
The IPR issues are solved; we should update our criteria to require 2.1 now.
