### ISSUE TITLE
See if parts of wiki page CA:BaselineRequirements need to be directly in CA Policy

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#46]
Need to check to see if there are parts of 
https://wiki.mozilla.org/CA:BaselineRequirements
that should be directly in the CA Policy.

**Comment by gerv** [comment]
@WilsonKathleen: I can see there's stuff on auditor performance there we need to keep, and perhaps we need to take inspiration from the section on audit scope when we are trying to address issue #36 on TCSCs. But it would help if you were able to do your own assessment of what on that page might need including, and list those things here. No rush :-)

**Comment by WilsonKathleen** [comment]
> https://wiki.mozilla.org/CA:BaselineRequirements
> 2.1 RFC 5280
I believe that compliance with RFC 5280 is checked by the auditors as part of the WebTrust and ETSI audits. So I don't think we need to add this to the Mozilla Root Store Policy.

> 2.2 Whole-Population Audit of Intermediate Certs
Perhaps it could be further clarified in section 3.1 of the Mozilla Root Store Policy by changing the first paragraph to:
"Before being included and periodically thereafter, CAs MUST obtain certain audits for their root certificates and all of their intermediate certificates that are not technically constrained to prevent issuance of working server or email certificates. This section describes the requirements for those audits."

> 2.3 WebTrust BR Audit Statement
> 2.3.1 Extended Validation
> 2.4 ETSI BR Audit Statement/Certificate

These are covered in section 3.1.2.1.

> 2.5 A CA's First BR Audit
Don't need to add to the Mozilla Root Store Policy

> 2.6 Auditor Qualifications
Covered in section 3.2.

> 2.7 Audit Mistakes
I don't think we should add this directly to the Mozilla Root Store Policy.

**Comment by gerv** [comment]
I added the improved wording that was suggested. I hope this means we can now delete that wiki page :-)

**Comment by WilsonKathleen** [comment]
> I hope this means we can now delete that wiki page :-)

We'll discuss offline, but there are a couple sections I think we should retain somewhere, maybe we need to have a wiki page whose audience is auditors...
https://wiki.mozilla.org/CA:BaselineRequirements#Audit_Mistakes
https://wiki.mozilla.org/CA:BaselineRequirements#Whole-Population_Audit_of_Intermediate_Certs
(the diagram and explanation are useful to auditors)
