### ISSUE TITLE
Add Requirements about what an Audit Statement must include

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#58]
Please update the CA policy to require that audit statements submitted to Mozilla MUST be public-facing (not confidential), provided in English, and must include:
- Name of the company being audited 
- Name and address of the organization performing the audit 
- Audit Criteria and version number that was used to audit each of the Roots respectively
- Audit Period Start and End date(s), where audit period is the period of time the auditor considers when assessing the work of a CA. It is usually a year-long period. The audit is supposed to analyze the certificate issuances carried out during this entire period. Audit periods must be continuous, i.e. no gaps.
- Friendly Name and SHA1 or SHA256 Fingerprint of each root certificate and intermediate certificate covered in the audit scope.
- Audit Statement Date must be within 90 days of the audit period end date
- For ETSI - the attestation should state that the audit was a full audit, and must indicate which parts of the criteria applied (e.g. DVCP, OVCP, NCP, NCP+, LCP, EVCP, EVCP+, Part1 (General Requirements), Part 2 (Requirements for trust service providers)).
~~

**Comment by WilsonKathleen** [comment]
I am looking into the possibility of changing this to requiring that all audit statements be accompanied by a transmittal letter that is in a particular format and contains specific information. This would be a good way to normalize the information that we get regarding all audit findings (independent of ETSI and WebTrust).

**Comment by gerv** [comment]
@WilsonKathleen: that sounds like a great idea. It solves the problem of interfering with the existing form of letter, which may have all sorts of restrictions and so on as to what it can and can't say.
