### ISSUE TITLE
Require full CP/CPS in English

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#6]
Kathleen proposes to insert a third bullet point into section 6 of the Inclusion section of the policy, stating:

<blockquote>
"- translate into English the Certificate Policy and Certification
Practice Statement documents pertaining to the certificates to be
included and the trust bits to be enabled;" 
</blockquote>

This proposal was discussed in m.d.s.policy and achieved a reasonable amount of support, although questions remain outstanding about how authoritative we should require the English version to be.
https://groups.google.com/forum/#!msg/mozilla.dev.security.policy/zCrSaJSHEwQ/_w0hOujsBwAJ

**Comment by gerv** [comment]
My proposal is that we allow the non-English version to be authoritative (as that's the working language of the CA) but require the CA to attest, as part of their submission, that the translation is not materially different.

**Comment by gerv** [comment]
@WilsonKathleen: do we want to require that this be true on an ongoing basis, or only when a CA is applying for inclusion?

**Comment by WilsonKathleen** [comment]
I think that question should be asked in m.d.s.policy

My personal opinion: we need the English translations of the documents for root inclusion/change requests. I don't plan on reviewing the documents for each CA every year, so I don't really need the English translation of every version of their CP/CPS. If there is a circumstance requiring me to review their CP/CPS, I can request the translation from the CA.

**Comment by gerv** [comment]
@WilsonKathleen: that works for you, but do we need to consider relying parties and the wider community? For better or worse, English is the working language of our community. If a CA has a significantly updated CPS and it's only available in Chinese, or Hindi, then it's hard for people to spot that they've made e.g. bad changes to their methods of domain validation.

CPs and CPSes don't change massively all the time. Once a CA has an English version, it's much less work to keep it up to date than it is to create it in the first place. So perhaps there's an argument, from simplicity and transparency, to simply require that all CPs and CPSes also be published in English...

**Comment by WilsonKathleen** [comment]
I'm totally fine with adding that requirement, if the m.d.s.policy community agrees.  Thanks!

**Comment by gerv** [comment]
This was agreed, and the following para will be added to section 5 of the CCADB policy:

> CAs must provide English versions of any Certificate Policy and Certification
> Practice Statement documents which are not originally in English, with version
> numbers matching the document they are a translation of. The English version is
> not required to be authoritative in all cases of dispute, but the CA must
> attest that the translation is not materially different to the original.
