### ISSUE TITLE
CCADB Policy section 3 - update to reflect Audit Cases

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#62]
CAs need to provide their annual updates (audit, CP/CPS, test websites) via the CCADB as described here:
https://wiki.mozilla.org/CA:CommonCADatabase#Updating_Audit_Information

**Comment by gerv** [comment]
@WilsonKathleen: can you provide appropriate text and say how to edit CCADB section 3 to say the right thing?

**Comment by WilsonKathleen** [comment]
Perhaps the last paragraph in section 3.1.3 can be updated to say:

"Audit reports which are being supplied to maintain a certificate within the Mozilla root program MUST be provided to Mozilla via the Common CA Database (CCADB) within three months of the point in time date or the end date of the period."

Where "Common CA Database (CCADB)" would be a link to 
https://wiki.mozilla.org/CA:CommonCADatabase#Updating_Audit_Information

**Comment by gerv** [comment]
I'd like to try and avoid links from policy docs to "howto" docs. I can certainly add a bit which reminds them that the way to submit audit reports is via the CCADB.
