### ISSUE TITLE
Better rules about what do when audits are qualified

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#68]
Currently, it's unclear how Mozilla views audits which are qualified (i.e. not clean). We should be more clear about what this means for the CA concerned.

**Comment by gerv** [comment]
One option is to require an incident report in m.d.s.p. for each audit qualification. That would then require the CA to explain what happened, how long it had been going on, how it was discovered, and what they've done to remediate the problem and deal with any possible misissuance.

Audit qualifications often cover multiple audits - if they are discovered during the audit process for one audit, the activity often has carried over into the audit *period* of the second audit. This should be acceptable if the CA explains in their incident report when remediation was, or is expected to be, complete.

**Comment by gerv** [comment]
@WilsonKathleen: any thoughts?

**Comment by WilsonKathleen** [comment]
Sounds reasonable, as long as it can be one bug per qualified audit, since usually there are multiple items noted in qualified audits, so it could balloon out into more bugs than we can keep up with.

**Comment by gerv** [comment]
Well, I'd hope qualified audits would be fairly rare, and only contain a small number of items... We can start by expecting one bug, but if we find the bugs get quite complicated, we can move to requiring one per item.

@WilsonKathleen: Do we need to put this in the policy, or is it sufficient simply that those who are reviewing audit reports (you? Aaron?) take a note that if you see a qualified one, we need to ask for an incident report?

**Comment by WilsonKathleen** [comment]
This does sound more like a process thing than a policy thing. I'll look into updating our process to file a Bugzilla bug whenever there is a qualified audit statement.
