### ISSUE TITLE
Kathleen's review of version 2.4.1

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#74]
Sorry it has taken me so long to get to this.  Overall, I think version 2.4.1 looks great! 

Below is a list of things I think should be updated/clarified.

Section 1, second paragraph:

- Change change “ours” to “Mozilla’s root store”. in
“Other entities distributing software based on ours are free to adopt their own policies.”

- This is in the old policy too, but in since I'm nit-picking...
“…and are also permitted to modify the values of the trust bits on CA certificates in the default CA certificate set.”
I think that makes it sound like they may modify the default CA certificate set.
Recommend changing to:
“In particular, under the terms of the relevant Mozilla license(s) distributors of such software are permitted to add or delete CA certificates and modify the values of the trust bits in the versions that they distribute.”

Section 1.1

- Change
“1. CA certificates applying for inclusion in, or included in, the Mozilla root store.”
to
“CA certificates included in, or under consideration for inclusion in, the Mozilla Root Store.”

- Change item 2 in a few places, enclosed by *:
“2. Intermediate certificates which have at least one valid, unrevoked chain up to such a CA certificate and which are not technically constrained *to prevent issuance of* working server or email certificates. Such technical constraints could consist of either:
    - an Extended Key Usage (EKU) extension which does not contain *any of these KeyPurposeIds: anyExtendedKeyUsage, id-kp-serverAuth, id-kp-emailProtection*; or:
    - name constraints which do not allow *Subject Alternative Names (SANs)* of any of the following types: dNSName, iPAddress, SRVName, rfc822Name

- Change the first bullet point in item 3 to:
“an Extended Key Usage (EKU) extension which contains one or more of these KeyPurposeIds: anyExtendedKeyUsage, id-kp-serverAuth, id-kp-emailProtection; or:”

Section 1.2

- Change the link for “CA Certificate module owner” to
https://wiki.mozilla.org/Modules/Activities#CA_Certificates

- In second paragraph change to
“The CA Certificate policy module team…”
and have “CA Certificate policy module” link to
https://wiki.mozilla.org/Modules/Activities#Mozilla_CA_Certificate_Policy

Section 4

- Change second sentence to:
“CAs with certificates in Mozilla’s root store MUST use the CCADB, …”

Section 5

The terms “Mozilla’s program” and “Mozilla’s CA Certificate Program” should be changed to Mozilla’s root store” to match the rest of the policy.

Section 5.3.1

I will create a separate issue for this:  If a root certificate only has the email trust bit set (does not have the SSL trust bit set) then their subCA certs don’t need to have the EKU, because they are already constrained in our program to S/MIME usage.

Section 7.1

change
“To request that its certificate(s) be added to the default set…”
to
“To request that its certificate(s) be added to Mozilla’s root store…”

Section 7.2

- Change occurrences of “currently included,” to “currently included in Mozilla’s root store,”

- “trust bits (Websites, Email)”
Throughout the rest of the document you say “SSL trust bit” and “email trust bit”
I don't really have a preference, as long as its consistent.
However, in all other documentation we use "Websites (TLS/SSL) trust bit".

Section 7.3

- Change “or removing them from Mozilla products.” to “or removing them from Mozilla’s root store.”

-  I don’t understand what “...unless a policy specifies a different rule” means. Can the CA specify such a policy? Or should it say "a Mozilla policy"?

Section 7.4

Change “All CAs whose certificates are distributed with our software products…”
to
“All CAs with certificates included in Mozilla’s root store…”

Thanks,
Kathleen

**Comment by dzacharo** [comment]
For Section 5.3.1, this is something that could change if the CA requests to set the Websites trust bit at a later time. I don't know how frequently this happens but it would create issues with existing subCAs if they are only meant to issue S/MIME Certificates.

**Comment by dzacharo** [comment]
I just saw that this is also raised in https://github.com/mozilla/pkipolicy/issues/75

**Comment by gerv** [comment]
> Change “ours” to “Mozilla’s root store”. in
“Other entities distributing software based on ours are free to adopt their own policies.”

I'm not sure this right. The issue here is people basing software on Firefox, not on the root store. Basing software on the root store doesn't have any trademark issues.

> [addition of anyEKU to scope section]

Are you sure? Firefox ignores anyEKU, so why do we care?

I've revamped section 1.2 to give details of both teams involved in the process, including the links you mention.

Other than that, I've made all of these changes.

**Comment by gerv** [comment]
@WilsonKathleen: when you have a moment, the above comment has a couple of queries for you.

**Comment by WilsonKathleen** [comment]
>> Change “ours” to “Mozilla’s root store”. in
>> “Other entities distributing software based on ours are free to adopt their own policies.”
>
> I'm not sure this right. The issue here is people basing software on Firefox, not on the root 
> store. Basing software on the root store doesn't have any trademark issues.

OK. Agree with leaving as-is

>>  [addition of anyEKU to scope section]
> 
> Are you sure? Firefox ignores anyEKU, so why do we care?

I care for two reasons:
1) Firefox is not the only user of the NSS root store.
2) In general, I think Mozilla's Root Store Policy should match the BRs whenever possible. In this case, I think that our use of "Technically Constrained" should match the definition in the BRs.

BR Section 7.1.5: "For a Subordinate CA Certificate to be considered Technically Constrained, the certificate MUST include an Extended Key Usage (EKU) extension specifying all extended key usages that the Subordinate CA Certificate isauthorized to issue certificates for. *The anyExtendedKeyUsage KeyPurposeId MUST NOT appear within this extension.*"

> I've revamped section 1.2 to give details of both teams involved in the process, 
> including the links you mention.
> 
> Other than that, I've made all of these changes.

Thanks!

I will review version 2.5, and create a separate issue if I notice anything else.

**Comment by gerv** [comment]
Filed new issue #79 on anyEKU.
