### ISSUE TITLE
Section 5.3.1 and root certs with only the Email trust bit set

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#75]
If a root certificate only has the email trust bit set (does not have the SSL trust bit set) then their subCA certs don’t need to have the EKU, because they are already constrained in our program to S/MIME usage.

Reference #4 in
https://wiki.mozilla.org/CA:CertificatePolicyV2.1#Frequently_Asked_Questions
"A subordinate CA certificate that transitively chains to a trust anchor that only has the email trust bit enabled may be considered technically constrained as per item #9 of Mozilla's CA Certificate Inclusion Policy even when it does not include an EKU extension. "

**Comment by WilsonKathleen** [comment]
Posted by dzacharo  in #74: For Section 5.3.1, this is something that could change if the CA requests to set the Websites trust bit at a later time. I don't know how frequently this happens but it would create issues with existing subCAs if they are only meant to issue S/MIME Certificates.

Response:
If a CA has a root cert with only the email trust bit enabled, and they want to enable the Websites trust bit, they have to go through the full root inclusion/update process again. So they will have to be re-evaluated and discussed before the Websites trust bit can be enabled.

Reference:
https://wiki.mozilla.org/CA:How_to_apply#Enable_Additional_Trust_Bits_for_an_included_root

**Comment by dzacharo** [comment]
Correct. However, if and when their application is approved, this problem will surface and their existing subcas for s/mime-only will not be technically constrained for s/mime anymore. This adds a risk that could be avoided if Mozilla forced the id-kp-emailProtection EKU in the s/mime constrained subcas.

**Comment by WilsonKathleen** [comment]
True, but there really are CAs that only want the email trust bit enabled for certain root certs.
If the case you describe ever does occur (not very common), we could just tell that CA to use a different/new root cert to get the Websites trust bit (which is preferred anyways).

**Comment by gerv** [comment]
We could make it a Recommended Practice that if a certificate chain contains EKU constraints, the immediately-issuing intermediate contains the same EKU constraints.
https://wiki.mozilla.org/CA/Required_or_Recommended_Practices

**Comment by gerv** [comment]
I've added the following to that wiki page under "Recommended":

> === Usage of Appropriate Constraints ===
> 
> Root certificates in Mozilla's program can have either the SSL trust bit set, or the Email trust bit, or both. If only one of those bits is set, relying software will trust certificates in that hierarchy for only that purpose. Nevertheless, it is a best practice for the immediately-issuing intermediate certificate to also contain EKU constraints of either id-kp-serverAuth or id-kp-emailProtection as appropriate, such that if the trust status of the root ever changes (or is not enforced for some reason), the end-entity certificates are still appropriately constrained.
