### ISSUE TITLE
Update policies allowed/required for ETSI audits

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#81]
In version 2.5, the 3.1.2.2 ETSI acronyms might need to be updated.

Per section 3.2 of
http://www.etsi.org/deliver/etsi_en/319400_319499/31941101/01.01.01_60/en_31941101v010101p.pdf
BRG Baseline Requirements Guidelines 
DVC Domain Validation Certificate 
DVCP Domain Validation Certificate Policy 
EVC Extended Validation Certifi
OVC Organizational Validation Certificate 
OVCP Organizational Validation Certificate Policy 

Version 2.5 of our policy currently says it should be:
    ETSI EN 319 411-1 - DVCP, OVCP, PTC-BR

I'm not sure what the correct update is, maybe ETSI folks can help, but I've seen
ETSI EN 319 411-1, NCP and the incorporated BRG-OVC
and
services also comply with the PTC-BRG requirements for OVC

**Comment by gerv** [comment]
I've emailed Arno to ask him if he can help us get this right.

**Comment by gerv** [comment]
Arno says the policy should read:

If being audited to the ETSI criteria, the following audits are required
(see section 3.1.1 for version numbers):

For the SSL trust bit, a CA and all subordinate CAs technically
capable of issuing server certificates must have either of the following:
        
        ETSI EN 319 411-1 - DVCP, OVCP, IVCP, EVCP,
	ETSI EN 319 411-2 - QCP-w,

For the email trust bit, a CA and all subordinate CAs technically
capable of issuing email certificates must have either of the following
sets of audits:
        
        ETSI EN 319 411-1 - LCP, NCP, NCP+
	ETSI EN 319 411-2 - QCP

And also, later:

For ETSI, a statement to indicate if the audit was a full audit, and which parts of the criteria were applied,  e.g. DVCP, OVCP, NCP, NCP+,LCP, IVCP, EVCP as defined in 319 411-1 "Requirements for Trust Service Providers issuing certificates Part 1: General requirements " and/or QCP as defined in
319 411-2  "Requirements for Trust Service Providers issuin certificates Part 2: Requirements for trust service providers issuing EU qualified certificates "

**Comment by dzacharo** [comment]
There is no "IVCP" specifically identified as a policy in ETSI EN 319 411-1 (v1.1.1). Policy identifiers are described in section 5.3.

Also, there is no "QCP" in ETSI EN 319 411-2 (v2.1.1). The policies described in this document in section 5.3 and could apply for s/mime capable certificates are:
- QCP-l
- QCP-l-qscd
- QCP-n
- QCP-n-qscd

**Comment by gerv** [comment]
@dzacharo: so do you know what the right answer is? I confess I'm a bit lost...

**Comment by dzacharo** [comment]
Sure. Replace "QCP" with the 4 different detailed QCP identifiers:
- QCP-l (for legal entities)
- QCP-l (for legal entities where the private key is generated in a QSCD, similar to FIPS 140-2 Level3)
- QCP-n (for natural persons)
- QCP-n-qscd (for natural persons where the private key is generated in a QSCD, similar to FIPS 140-2 Level3)
Note: "QSCD" stands for "Qualified Signature Creation Device" which sets some criteria for crypto-tokens.

For SSL Certificates, you can just remove "IVCP" from the audit scope. A CA that is audited against "OVCP" ETSI policy identifier, it definitely qualifies for the "IV" (2.23.140.1.2.3) OID of the CABF BRs.
Hope this helps.

**Comment by gerv** [comment]
After a 20-minute chat with Ryan, I think this is where we need to be:

If being audited to the ETSI criteria, the following audit requirements apply
(see section 3.1.1 for version numbers):

*   For the SSL trust bit, a CA and all subordinate CAs technically
    capable of issuing server certificates must have one of the
    following audits, with at least one of the noted policies or sets of policies:

    * [ETSI TS 102 042][ETSI-102-042] (DVCP, OVCP, or PTC-BR)
    * [ETSI EN 319 411-1][ETSI-319-411-1] (LCP and (DVCP or OVCP)) and/or (NCP and EVCP)
    * [ETSI EN 319 411-2][ETSI-319-411-2] (QCP-w)

*   For the email trust bit, a CA and all subordinate CAs technically
    capable of issuing email certificates must have one of the
    following audits, with at least one of the noted policies:

    * [ETSI TS 101 456][ETSI-101-456]
    * [ETSI TS 102 042][ETSI-102-042] (LCP, NCP, or NCP+)
    * [ETSI EN 319 411-1][ETSI-319-411-1] (LCP, NCP, or NCP+)
    * [ETSI EN 319 411-2][ETSI-319-411-2] (QCP-l, QCP-l-qscd, QCP-n,
      or QCP-n-qscd)
