### ISSUE TITLE
Update URL for Common CCADB Policy

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#82]
New canonical URL is: http://ccadb.org/policy .

**Comment by floatingatoll** [comment]
Is the absence of https:// here intentional?

**Comment by gerv** [comment]
Github Pages with custom domains don't yet support HTTPS :-(
https://github.com/isaacs/github/issues/156

Ironic, perhaps. But this was the least-resistance way to get the website up at all.
