### ISSUE TITLE
Update links in section 7.2

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#84]
https://wiki.mozilla.org/CA:How_to_apply
has been moved to
https://wiki.mozilla.org/CA/Application_Instructions

https://wiki.mozilla.org/CA:Root_Change_Process
has been moved to
https://wiki.mozilla.org/CA:Root_Change_Process

**Comment by WilsonKathleen** [comment]
Oops. Root Change Process page hasn't been moved yet, and still needs to be updated. I added that to my list of things to do...

**Comment by gerv** [comment]
I've fixed the first of these.
