### ISSUE TITLE
Re-check the new auditor related verbiage in version 2.5 re rejecting an auditor

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#87]
Noted in a recent email:
~~
2.5 guts the provision that allows Mozilla to _reject_ an auditor in the reworded Section 3.2 in https://github.com/mozilla/pkipolicy/blob/master/rootstore/policy.md (or, Item 15 and Item 16 in Root Store Policy 2.3 - https://github.com/mozilla/pkipolicy/blob/2.3/rootstore/policy.md )

... the burden should be on the CA to establish they're doing things right
~~

**Comment by gerv** [comment]
It's now bullet 2 in section 2.3, which deals with the exceptions or modifications we make to the Baseline Requirements:

> Mozilla reserves the right to accept audits by auditors who do not meet the qualifications given in section 8.2 of the Baseline Requirements, or refuse audits from auditors who do.

**Comment by WilsonKathleen** [comment]
OK. That seems fine to me.
