### ISSUE TITLE
Clarify requirement for full annual period-of-time audits

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#89]
The rules for full annual period-of-time audits as stated in the BRs need to be repeated directly in Mozilla's policy, because there are included root certs that only have the Email trust bit set (so the BRs don't apply to them).

I think we need to clarify in the current version of Mozilla's root store policy that the full surveillance/period-of-time audits must be provided each year and that there must not be any period of time that is not audited.

Section 3.1.2 lists the acceptable audit criteria, so perhaps that section should begin with a sentence such as:
"Full surveillance period-of-time audits according to the criteria listed below must be obtained annually and must cover audit periods that are less than one year and are contiguous."
(need to check with audit folks on the terminology -- trying to say that an agreed-upon-procedure audit is not sufficient, it needs to be a full audit)

And at the end of section 3.1.3, add:
"Point-in-time audit statements may be used to confirm that all of the problems that an auditor previously identified in a qualified audit statement have been corrected. However, a point-in-time assessment does *not* replace the period-of-time assessment."

**Comment by gerv** [comment]
@WilsonKathleen:

> The rules for full annual period-of-time audits as stated in the BRs need to be repeated directly in Mozilla's policy

They are; it's just that they are in the CCADB section. Draft policy 2.5 currently says: "Mozilla manages its root program using the Common CA Database (CCADB). CAs with certificates in Mozilla’s root program MUST use the CCADB". Is that actually true for email-only CAs? If not, we need to fix the scope of that statement. We should then move the yearly-audit requirement out of the CCADB section and into the main Audit section, as you say.

(Can you confirm we do have at least one email-only CA, and this discussion is not merely theoretical?)

**Comment by WilsonKathleen** [comment]
>> Can you confirm we do have at least one email-only CA
Deutscher Sparkassen Verlag GmbH (S-TRUST, DSV-Gruppe)

I just re-read the CCADB policy, and did not find where it says that a full period-of-time audit is required annually, that the period-of-time between audit statements must be contiguous, and that point-in-time audits do not replace period-of-time audits.

So, I think this information needs to be added, and I think the correct place to add it is directly in Mozilla's Root Store Policy, as indicated above.

**Comment by gerv** [comment]
@WilsonKathleen : How's this for a new section 3.1.3?

#### 3.1.3 Audit Parameters ####

Full-surveillance period-of-time audits MUST be conducted and updated audit
information provided no less frequently than **annually**. Successive audits
MUST be contiguous (no gaps).

Point-in-time audit statements may be used to confirm that all of the problems
that an auditor previously identified in a qualified audit statement have been
corrected. However, a point-in-time assessment does not replace the
period-of-time assessment.

Audit reports which are being supplied to maintain a certificate within the
Mozilla root program MUST be provided to Mozilla via the CCADB within three
months of the point-in-time date or the end date of the period.

**Comment by WilsonKathleen** [comment]
The new text looks good to me, but it is not clear to me where this is going to be added.

In https://github.com/mozilla/pkipolicy/blob/master/rootstore/policy.md section 3.1.3 lists the information that must be included in audit statements.  I need that information to remain in the policy.
So, will this new text be added to the bottom of that section? Or will there be a new section 3.1.4 added below it?

**Comment by gerv** [comment]
The idea is that this would be 3.1.3, and the current 3.1.3 would become 3.1.4 (as logically, this content comes before the section on what the public audit information needs to say).

**Comment by WilsonKathleen** [comment]
Sounds good to me. Thanks!
