### ISSUE TITLE
Codify requirements relating to Common CA Database (Salesforce) into the policy

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#9]
CAs are being asked to take various actions to update the CCADB, such as disclose intermediate certificates, but the rules surrounding this are not in the Mozilla policy. They should be formalised in policy form and either added to the existing policy, or turned into a new policy document whose maintenance is shared and whose contents are agreed with other CCADB members.

**Comment by gerv** [comment]
Hmm. That commit didn't intentionally reference this issue. Anyway...

Note that there are some parts of the existing policy which would need updating even if the CCADB policy were a separate document.

**Comment by gerv** [comment]
WilsonKathleen: Could you please quickly go through the policy and make a list of the sections which would need to change to take into account the fact that we are now using the CCADB?

I think I prefer the idea of having a separate CCADB policy document, and having our policy say:

<blockquote>
Information about the CA's certificates and operations are maintained in the Common CA Database (CCADB). CAs should follow the requirements of the CCADB policy as a condition of continued membership in the Mozilla root program.
</blockquote>

**Comment by WilsonKathleen** [comment]
I guess it depends on how much we need to put into the policy versus keeping with the instructions in the wiki page.

If we try to incorporate CCADB stuff into the current CA policy, here's where I think we would need to add/change things.

= Applying for Inclusion of Root Certificates in Mozilla Products =

6. We require that all CAs whose certificates are distributed with our software products:
-> need policies, audits for subCAs to be disclosed in CCADB

8. All certificates that are capable of being used to issue new certificates, and which directly or transitively chain to a certificate included in Mozilla’s CA Certificate Program, MUST be operated in accordance with Mozilla’s CA Certificate Policy and MUST either be technically constrained or be publicly disclosed and audited.
-> Disclosed in CCADB

10. We recognize that technically constraining subordinate CA certificates as described above may not be practical in some cases. All certificates that are capable of being used to issue new certificates, that are not technically constrained, ...
-> Disclosed in CCADB
-> Update bullet points to match or point to https://wiki.mozilla.org/CA:SalesforceCommunity#Which_intermediate_certificate_data_should_CAs_add_to_Salesforce.3F

= Maintaining Confidence in Included Root Certificates =
2. CAs must revoke Certificates ..
-> And update the corresponding intermediate cert records in CCADB, to indicate revocation status, so it gets added to OneCRL.

3. We require that all CAs whose certificates are distributed with our software products provide us an updated statement annually of attestation ...
-> Applies to updating audit statements for the intermediate certs in CCADB that are not explicitly mentioned in the CA's audit statements

5. We require that all CAs whose certificates are distributed with our software products notify us when its policies and business practices change...
-> I think the BRs require CP/CPS to be updated annually. If that is the case, we should adopt that, add dates for CP/CPS to CCADB, etc.
-> Applies to intermediate certs in CCADB too

6. We require that all CAs whose certificates are distributed with our software products ensure that we have their current contact information.
-> In CCADB 

7. A failure to provide required notifications or updates as specified in items #4, #5, and #6 in a timely manner shall be grounds for disabling a CA’s root certificates or removing them from Mozilla products. 
-> updates to CCADB

-> Somewhere in this section would need to put requirements about when CAs have to disclose new intermediate certs in CCADB, and their corresponding audits, CP/CPS.

= Enforcing the Mozilla CA Certificate Policy =
Not sure if we need to specifically call out intermediate certs and OneCRL in this section.
