### ISSUE TITLE
CCADB Policy: Update Section 4 to recognize constraints at the root cert level

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#93]
To satisfy the CCADB requirement that certificates that are not technically constrained must be disclosed in the CCADB (with public facing CP/CPS and audit documents), some root store operators may need to apply the technical constraints at the root certificate level.

We should update Section 4 of the CCADB Policy to account for this situation.

One solution is to modify the bullet point in the list of exempt intermediate certificates, which currently says:
"The root certificate(s) to which the certificate chains up is/are not trusted for server authentication by any Store; or"

Suggested new text:
"The root certificate(s) to which the certificate chains up is/are domain constrained or not included by every Store; or"

**Comment by gerv** [comment]
I'm not sure that edit would have quite the effect you intend. Making rules which only apply when a certificate is included by every store, means that as soon as a new store joins the CCADB, the rules for some certificates might change even though nothing has changed about those certs or the stores in which they are included. That seems non-ideal.

As I understand it, the idea here is to allow an exemption from disclosure for subCAs if there are domain constraints at the root level. This exemption may not be permitted by all stores, but those who do not wish to permit it can include a requirement in their own policies which is more strict.

I would therefore propose we fix this by adding a new bullet to that list, which says something like (based on an existing bullet):

> The root certificate to which the intermediate certificate chains up has the Extended Key Usage (EKU) extension and the EKU includes the anyExtendedKeyUsage or id-kp-serverAuth KeyPurposeIds, and the certificate is name constrained as described in section 7.1.5 of the CA/Browser Forum’s Baseline Requirements; or

@WilsonKathleen: would that do the job, or does that not adequately describe the certificates in question?

We should also switch that list to be a numbered list, to make it easier to reference individual items in root store policies.

**Comment by WilsonKathleen** [comment]
The certificates in question don't have those types of constraints. Rather, the root store constrains them via code. So, that particular change will not help.

**Comment by WilsonKathleen** [comment]
Currently the policy says:
"The root certificate(s) to which the certificate chains up is/are not trusted for server authentication by any Store; or"

I would just like to update this bullet point to add an exception for root store operators who are constraining certain root certificates via their own code and do not want/expect those CA hierarchies to be disclosed in the CCADB. Of course this does not apply to Mozilla.

**Comment by WilsonKathleen** [comment]
Thinking about this some more, my initial suggestion was bad. While I want to allow an out for root store operators, I don't want to allow an out for CAs (who we/Mozilla might be constraining).

So, perhaps a better solution would be to add a separate bullet point that says something like:
"Specific Store policies may provide additional exemptions."

**Comment by gerv** [comment]
@WilsonKathleen: I think that if what the store concerned wants is to add additional exemptions, then indeed these are best done using store-specific policy. Can we pass that message on, and get confirmation that they are OK with that solution? I am happy to change from bullets to numbers if that helps them.

**Comment by WilsonKathleen** [comment]
Closing this issue. Additional exemptions will be handled specially by each root store operator.
