### ISSUE TITLE
Confusion about Last sentence of item 3 of Section 2.2 of Mozilla Root Store Policy

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#94]
Section 2.2 of Version 2.5 of Mozilla Root Store Policy says:
"3. For a certificate capable of being used for SSL-enabled servers, the CA must ensure that the applicant has registered the domain(s) referenced in the certificate or has been authorized by the domain registrant to act on their behalf. This must be done using one or more of the 10 methods documented in section 3.2.2.4 of version 1.4.1 (and not any other version) of the CA/Browser Forum Baseline Requirements. The CA's CP/CPS must clearly specify the procedure(s) that the CA employs, and each documented procedure should state which subsection of 3.2.2.4 it is complying with. *Even if the current version of the BRs contains a method 3.2.2.4.11, CAs are not permitted to use this method.*"

The last sentence is causing confusion for some CAs.

We intend that last sentence to mean that "any other method" must be one of the 10 methods listed in version 1.4.1 of the BRs.

**Comment by gerv** [comment]
@WilsonKathleen: how about this as a rewording?

Even if the current version of the BRs contains a method 3.2.2.4.11 ("any other method"), CAs are not permitted to use methods of domain validation which are not among the 10 permitted methods.

**Comment by WilsonKathleen** [comment]
Sounds good to me. Thanks!
