### ISSUE TITLE
Consider moving root store to independent releases, new format

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#97]
The Mozilla Root Program's root store is currently stored as certdata.txt in the NSS tree. It has been suggested that there are advantages to it being an independently-released data store with its own release schedule, which NSS (and other consumers) then regularly take drops of onto whatever branch is appropriate. 

Secondly, this might be an opportunity to use a richer format to maintain the root store information (which could be converted back to certdata.txt format whenever NSS took a root store release). The aim of switching format would be to include some of the data currently maintained elsewhere (see https://wiki.mozilla.org/CA/Additional_Trust_Changes) such as EV status and OIDs, imposed name constraints, and dates when trust was removed. We would want to retain or even enhance the human readability level of the information compared to certdata.txt.

There was a discussion in m.d.s.p. about this:
https://groups.google.com/forum/#!topic/mozilla.dev.security.policy/--aa6dYHhrc

There are various existing formats which were suggested as possibilities:
http://www.etsi.org/deliver/etsi_ts/119600_119699/119612/02.02.01_60/ts_119612v020201p.pdf
http://unmitigatedrisk.com/?p=259
Trust Anchor Management Protocol (TAMP - RFC5934)
https://datatracker.ietf.org/doc/draft-belyavskiy-certificate-limitation-policy/

Providing a format which could encode any possible trust variance Mozilla might imagine is an anti-goal. However, some of the most common ones, like TLD restrictions and dates after which no new certs should be trusted, could certainly be supported.

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1294150

**Comment by wthayer** [comment]
This issue, while related, should be addressed separately from the Root Store policy.

**Comment by WilsonKathleen** [comment]
Instead of parsing certdata.txt, we recommend that people use the links provided on the [Common CA Database (CCADB) Resources tab](https://www.ccadb.org/resources), which provide lists of root certificates that are being curated for the purposes of Code Signing, Email (S/MIME), and Server Authentication (SSL/TLS).
