### ISSUE TITLE
Require CAs to support problem reports via email

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#98]
Section 4.9.3 of the CA/Browser Forum's Baseline Requirements says:

> "The CA SHALL provide Subscribers, Relying Parties, Application Software Suppliers, and other third parties with clear instructions for reporting suspected Private Key Compromise, Certificate misuse, or other types of fraud, compromise, misuse, inappropriate conduct, or any other matter related to Certificates. The CA SHALL publicly disclose the instructions through a readily accessible online means." 

Mozilla has made a central list of these mechanisms in the CCADB but, as it turns out, some of them (such as web forms with CAPTCHAs) are a pain to use. It is proposed that Mozilla policy go above and beyond that requirement to say that email must be one of the problem reporting methods supported.

**Comment by rmhrisk** [comment]
Recently someone has proposed a .well-known mechanism to provide contact details relating to security, see https://github.com/EdOverflow/security-txt maybe something like this could be useful for this case. This could make the contact details more uniformly discoverable to those outside the WebPKI community.

**Comment by gerv** [comment]
@rmhrisk it seems clear from discussion that this info is not per-CA, or even per-domain; in some circumstances (such as e.g. Google and Apple's sub-CAs) it's per-intermediate. So I think a .well-known mechanism probably won't do the trick, as mapping intermediates to their owners' domains is non-trivial.

**Comment by wthayer** [comment]
This issue was discussed but no agreement was reached: https://groups.google.com/d/msg/mozilla.dev.security.policy/AclrNBzklBo/OKLx6HkuCAAJ
