### ISSUE TITLE
For new inclusions, require all existing unexpired unrevoked certs in hierarchy to be BR compliant

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#99]
For new root inclusions, we should require that all existing unexpired unrevoked certs in the hierarchy be BR compliant. To do otherwise is to allow Firefox to recognise non-BR-compliant certs, which we want to avoid.

CAs would have flexibility in how they met this requirement. Clearly this is trivial for a CA asking to include a new root, it's more of an issue for existing roots. One option would be to revoke all non-compliant certs. Another would be to stand up a new root for inclusion, and cross-sign it with the old one.

m.d.s.p. discussion: https://groups.google.com/forum/#!topic/mozilla.dev.security.policy/2vBlRyfwxEs

**Comment by tdelmas** [comment]
What about non-BR-compliant unexpired revoked certs for which FF can't check the revocation status because of the non-compliance? (for example, https url for CRL)

**Comment by gerv** [comment]
If the CA can't get to the right place by revoking certs, they'll need to do the new-cross-signed-root approach or similar. "CAs would have flexibility in how they met this requirement", but they need to meet it somehow.
